### ISSUE TITLE
Spinlock API 구조화

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#121]
# 최신화 : 2020-09-27 10:57 AM

- [x] bio.rs -> struct Bcache : 3055104fd188b5396307847108f064e11bde3687
- [x] console.rs -> struct Console : deb882dc7494ade121ef379c0ce666b425c1fde4
- [ ] log.rs -> struct Log
- [ ] pipe.rs -> struct pipe
- [ ] proc.rs - > struct Proc
- [ ] virtio_disk.rs

- xv6에서는 데이터를 보호할 때 Spinlock을 사용합니다. 데이터에 접근할 때 `acquire()`로 lock을 쥐고, `release()`로 lock을 놓는 방식입니다.
- 현재 Spinlock을 사용하는 struct들은 아래 `Console` 예시와 같이 struct 내부에 Spinlock을 가집니다. 
https://github.com/kaist-cp/rv6/blob/bb28fa44b435d365b1d8620df4abc8d0552ba2d8/kernel-rs/src/console.rs#L13-L25
- Rust의 장점을 더욱 살리기 위해, **struct 안에 Spinlock을 놓기보다는 `Spinlock<T>`와 같은 형식으로 사용하게 바꿔야합니다.** 이 때 `T`는 데이터의 타입입니다. [cs492-concur Spinlock 참고](https://github.com/kaist-cp/cs492-concur/blob/master/lock/src/spinlock.rs)
- Spinlock을 갖는 struct 내부에서 Spinlock에 의해 보호되는 필드가 한 개인 경우, 전체 struct의 타입이 아닌 그 필드의 타입을 갖는 Spinlock을 사용해야 합니다.
  - 설명을 위해 실제 코드와 무관하게 예를 들겠습니다. `Console`에서 Spinlock을 이용해 보호하려는 필드가 `r`뿐이라면, `Spinlock<Console>`이 아닌 `Spinlock<u32>`를 사용하는 것이 적절합니다.
- Spinlock을 갖는 struct 내부에서 Spinlock에 의해 보호되는 필드가 여러 개인데 서로 독립적이라면, 각 필드마다 Spinlock을 사용하는 것이 적절합니다. 이를 정확히 구현하기 위해서는 **더욱 깊은 C 코드 이해가 필요합니다.**

부족한/잘못된 내용이 있으면 코멘트 부탁드립니다!

**Comment by jeehoonkang** [comment]
- 일단 모든 rawspinlock/rawsleeplock 등을 spinlock/sleeplock 등으로 바꿨습니다.
- 아직 어떤 lock이 어떤 data를 보호하는지 명확하지 않은 부분도 있는데, 앞으로 unsafe를 줄여가면서 해결하는 것으로 하겠습니다.
