### ISSUE TITLE
CVoid type handling

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#132]
Need to handle CVoid.
- 대체가 필요한지.
- 필요하다면 대체할 방향성은 무엇인지.

논의가 필요합니다.

**Comment by kimjungwow** [comment]
현재 libc::CVoid는 6개의 함수에서 사용되며, 3가지 기준으로 나눌 수 있습니다.
1. `proc.rs`의 함수
`either_copyout, either_copyin` : #226 을 진행하며 서윤님께서 리팩토링하실 계획입니다
2. `ptr`의 함수
`ptr::copy, ptr::write_bytes` : libc::CVoid를 u8로 대체 가능해보입니다
3. `kalloc.rs`의 함수
`freerange, kfree` : libc::CVoid를 u8로 대체 가능해보입니다
