### ISSUE TITLE
About refactoring

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#154]
파일을 나눠서 rust idiomatic 하게 refactoring 할 때, 가능하면 함께 해결되면(commit을 나눠서) 좋을 것 같은 minor issue들 목록입니다. 여러 파일에 대해 horizontal 하게 작업하면 효율이 떨어진다고 판단되는 것들입니다(*직접 해보고...).

#93 - 무의미한 casting 제거와 복잡한 logic(type casting, for, if, while, etc.) 단순화
#96 - `struct`, `fn` 등에 남아있는 불필요한 pub 제거
#137 - parameter, local variable type들 개발자의 의도에 맞게 변경. #151 의 `Procstate`(to `enum`)이나 `intena`(`i32` -> `bool`) 등의 변경 사항을 참고하시면 될 것 같습니다
#138 `wrapping_{}` operator vs `+-*/%` 중 의도에 맞는 설정
#149 variable name이 지나치게 함축적인 경우. ex: `intena` -> `interrupt_enabled`

추가로 comment에 문장 첫 글자 capitalize, 마지막에 마침표 등의 내용도 틈틈이 수정하면 좋을 것 같습니다.

+(8/26/2020) unsafe block을 조금 더 narrow 하게 좁힐 수 있는 경우 판단하여 compress 하면 좋을 것 같습니다.

저는 현재, `kernel_main.rs` 에서 호출하는 순서대로 진행 중입니다.

- [x] proc.rs / proc.c / proc.h
- [x] console.rs / console.c
- [x] printf.rs / printf.c
- [ ] kalloc.rs / kalloc.c
- [ ] vm.rs / vm.c
- [ ] trap.rs / trap.c
- [ ] plic.rs / plic.c
- [ ] bio.rs / bio.c
- [ ] fs.rs / fs.c / fs.h
- [ ] file.rs / file.c / file.h
- [ ] virtio_disk.rs / virtio_disk.c

[그 외에 진행해야할 부분]
- [ ] bio.rs / bio.c
- [ ] exec.rs / exec.c / exec.h
- [ ] log.rs / log.c
- [ ] pipe.rs / pipe.c
- [ ] sleeplock.rs / sleeplock.c
- [ ] spinlock.rs / spinlock.c
- [ ] start.rs / start.c
- [ ] string.rs / string.c
- [ ] syscall.rs / syscall.c / syscall.h
- [ ] sysfile.rs / sysfile.c
- [ ] sysproc.rs / sysproc.c
- [ ] trap.rs / trap.c
- [x] uart.rs / uart.c
- [ ] vm.rs / vm.c

[위의 작업들 필요없는 곳]
- elf.rs / elf.h
- buf.rs / buf.h
- fcntl.rs / fcntl.h
- param.rs / param.h
- etrace.rs / abort.rs / lib.rs / utils.rs
- memlayout.rs / memlayout.h
- kernel_main.rs / main.c
- stat.rs / stat.h
- riscv.rs / riscv.h
- virtio.rs / virtio.h

해당 작업 중 horizontal 한 작업이 더 좋다고 생각되는 이슈가 있다고 생각되시면 의견 주시면 감사하겠습니다.
추가로, 여기에 다 모아놨으니 위의 issue들을 close 하는 것이 좋을까요?

**Comment by jeehoonkang** [comment]
어느정도 해결된 것으로 보입니다.
