### ISSUE TITLE
sleeplock 리팩토링

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#189]
## 2020-10-06 : 우선 Inode에 SleeplockWIP을 적용해보는 중입니다

- PR #185 의 [코멘트](https://github.com/kaist-cp/rv6/pull/185#issuecomment-682341347)에서 논의된 대로, **Sleeplock 또한 Spinlock<T> 처럼 보호하는 데이터를 field로 가지고 있는 타입으로 만드는 게 맞다고 생각합니다.**

**Comment by jeehoonkang** [comment]
RawSleeplock은 이제 Buf에만 남았습니다.  #196 에서 이어가겠습니다.
