### ISSUE TITLE
실패할 수 있는 함수가 Result를 리턴하도록 수정하기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#203]
`pipe::alloc()` 와 같이 함수가 실패할 수 있으며, 실패하는 경우 -1를 리턴하도록 하여 실패하는지 확인하는 함수들이 있습니다. 이 함수들이 Rust의 `Result`를 리턴하도록 변경해야 합니다.

> (후속 PR에서) `Pipe::alloc` 이 `Result<(*mut File, *mut File), ()>` 을 리턴하도록 바꾸어 주세요. 다른 함수들도 실패할 수 있는 경우 모두 이런 형태로 바꾸기를 부탁드립니다.

_Originally posted by @efenniht in https://github.com/kaist-cp/rv6/pull/202#discussion_r484516856_

**Comment by jeehoonkang** [comment]
일단 제 눈에 보였던건 모두 result를 리턴하도록 리팩토링된 것으로 보입니다.  앞으로 구체적인 사례가 보일때마다 그때그때 적용하면 될 것 같습니다.
