### ISSUE TITLE
proc.rs refactoring

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#204]
Proc, Proc manager(PROC), Context(myproc)

각각에 대해 관련된 함수들 type system을 이용하여 idiomatic 하게 표현해야 합니다.

points.
1) ProcInner(임시 명칭) 만들어서 lock 잡기. 
2) struct RunningProc { ptr: *mut Proc } 만들어서 Cpu의 field proc의 type으로 사용하기
3) file 분리하여 process 폴더 안에 넣기
4) CPUS to CpuManager
5) PROC to ProcessManager
6) Context 다루기
7) Scheduler type implementation.

**Comment by coolofficials** [comment]
5번 이슈 #214 에서 진행.
struct ProcessSystem {
    process_pool: [Proc; NPROC] 
}

으로 변경함.

https://github.com/kaist-cp/rv6/pull/214#discussion_r489569370
https://github.com/kaist-cp/rv6/pull/214#discussion_r489517952

는 Proc을 Spinlock으로 감싼 이후에 진행해야함.

**Comment by coolofficials** [comment]
https://github.com/kaist-cp/rv6/pull/212#discussion_r495542331

**Comment by anemoneflower** [comment]
Remove `uninit()` from `PageTable` and `UserMemory`.
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/vm.rs#L295-L300
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/vm.rs#L412-L417
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/vm.rs#L374-L379

**Comment by coolofficials** [comment]
이미 다른 이슈들에서 작업을 잘 나눠서 진행하는 것으로 생각되어 닫겠습니다
