### ISSUE TITLE
pipe.rs : read/write용 channel의 주소가 같음

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#215]
https://github.com/kaist-cp/rv6/blob/f84b36ca0667a669d344a319e42751d8b9910c0c/kernel-rs/src/pipe.rs#L29-L37

현재 위와 같이 struct `Pipe`가 정의되어 있는데, struct `WaitChannel`은 zero-sized로 정의되어 있습니다. 따라서 `read_waitchannel`와 `write_waitchannel`의 주소가 같습니다. struct `WaitChannel` 안에 어떤 필드를 넣어서 이를 해결할지 논의해야 합니다.

https://github.com/kaist-cp/rv6/blob/f84b36ca0667a669d344a319e42751d8b9910c0c/kernel-rs/src/proc.rs#L204

**Comment by jeehoonkang** [comment]
`u8`을 추천합니다.  바이트가 가장 만만할 것 같아서..
