### ISSUE TITLE
Pipe 초기화 잘 하기

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/rv6#217]
`AllocatdPipe::alloc` 에서 메모리 할당을 몰아서 하기 위해서 덜 idiomatic한 코드가 만들어졌습니다. (https://github.com/kaist-cp/rv6/pull/211#discussion_r490136198) 할당했지만 아직 초기화되지 않은 상태를 타입으로 만들면 됩니다. `RcPool<T>` 가 할당한 메모리는 항상 `T` 가 내부에 있음을 가정하므로, 이를 사용하는 쪽에서는 safe하게 만들기 어렵고, `pool.rs` 에 타입을 추가해야 할 것 같습니다.

**Comment by kimjungwow** [comment]
> 구두로 말씀드렸던대로, mutable access는 alloc하는 시점에만 가능합니다. 이를 표현하기 위해 지금 API를 유지하고자 합니다.
https://github.com/kaist-cp/rv6/pull/250#issuecomment-714068798

allocation과 초기화를 나눠서 하는 것 ( #250 ) 대신, 맨 처음에 allocation할 때만 값을 입력 가능한 현재의 구현을 유지하기로 했습니다. 이를 유지하며 Pipe 초기화를 잘 할 방법이 있을까요? @efenniht

**Comment by kimjungwow** [comment]
상욱님께서 주신 의견 공유합니다.

a00a09c9b039309bf1c9e89331281f1308cf2717 해당 커밋이 pipe 초기화를 할 때 RcFile 할당에 실패하면 File 이 중간에 drop 되면서 문제가 발생할 수 있을 것 같습니다. 이 문제를 해결해야 할 것으로 보입니다.

**Comment by Medowhill** [comment]
현재 코드에서는 이 이슈에서 설명하는 문제가 발생하지 않는 것 같습니다. 다만, `ptr`이 초기화된 `Pipe`에 대한 포인터가 아니기 때문에, `as_mut` 대신 `as_uninit_mut`(<https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.as_uninit_mut>)을 사용해야 할 것으로 보입니다.

https://github.com/kaist-cp/rv6/blob/8badfb7bff5aa7a00f5afbad62d703f29c4ad24e/kernel-rs/src/pipe.rs#L137-L140
https://github.com/kaist-cp/rv6/blob/8badfb7bff5aa7a00f5afbad62d703f29c4ad24e/kernel-rs/src/pipe.rs#L150
