### ISSUE TITLE
FileType::Inode 의 off field 를 보호하는 타입 만들기

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/rv6#218]
design:

```rust
struct InodeHandle {
    ptr: Rc<SleepLock<Inode>>,
    off: UnsafeCell<usize>,
}
```

`Inode` 의 lock 을 건 상태에서만 `off` 를 접근할 수 있는 타입을 만들어야 합니다. (https://github.com/kaist-cp/rv6/pull/211#discussion_r489970751)

**Comment by kimjungwow** [comment]
1. `Sleeplock\<Inode\>`를 위해 #191 에서 진행했던 Sleeplock 리팩토링을 우선 진행하면 될까요?
1. `Rc`도 저희가 직접 구현하는 것이 맞나요?

**Comment by efenniht** [comment]
1. 네 맞습니다. 먼저 Inode 를 Sleeplock 으로 wrapping해야 합니다.
 2. 네. `FTABLE` 에서 사용했던 것과 비슷하게 만들 수 있을 것 같습니다.
