### ISSUE TITLE
Rust 코드 포맷 통일하기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#22]
[#20의 코멘트](https://github.com/kaist-cp/rv6/pull/20#discussion_r460394047)처럼 Rust 코드 포맷을 통일해야 합니다.

먼저 Rust 코드 포맷을 어떻게 통일할지 이야기하기 위해 이슈를 생성합니다.

1. ~100 글자 정렬~ default 값으로 하기로 했습니다.
  - `rustfmt`의 configuration을 통해 가능할 것으로 보입니다. 제가 `kernel-rs` 디렉토리 안에 `rustfmt.toml`을 만들어서 PR을 올리겠습니다. 이후 `kernel-rs` 디렉토리에서 `cargo fmt`를 실행하면 `rustfmt.toml`의 설정대로 `rustfmt`가 실행됩니다.
  - 그 외에 `rustfmt`의 configuration을 통해 설정할 포맷은 [rustfmt 문서](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)를 참고하여 `rustfmt.toml`을 수정해주시면 됩니다.
2. 처음에 newline으로 시작하지 않기
3. 함수 주석과 함수 정의 사이에 newline 없애기?
  - 예시 : [`console.rs::91`](https://github.com/kaist-cp/rv6/blob/dbd78ef716f1ee26e04e2c46d0f07a286fd96682/kernel-rs/src/console.rs#L91)의 newline을 없애기

이 외에 어떤 것들을 통일할지, 2번과 3번을 일일히 수정하지 않고 할 방법이 있는지를 같이 고민하면 좋겠습니다!

**Comment by jeehoonkang** [comment]
어느정도 마무리된 것으로 보입니다.
