### ISSUE TITLE
sysfile.rs:sys_open() : 중복되는 코드 줄이기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#220]
`sysfile.rs`의 `sys_open()`에 아래 코드가 여러 번 반복됩니다.

이러한 중복은 scopeguard 를 쓰거나 Drop 에서 이 작업을 해주는 다른 타입을 만들어서 해결해야 합니다.

_Originally posted by @efenniht in https://github.com/kaist-cp/rv6/pull/211#discussion_r491674207_

**Comment by efenniht** [comment]
아마 누군가 syscall 을 맡아서 리팩토링해야 할 것 같습니다. syscall에서 호출하는 내부 함수들의 리팩토링이 끝나면 시작할 수 있습니다.

**Comment by anemoneflower** [comment]
현재 코드에서는 `drop`을 통해 해결된 issue인 것 같습니다.
