### ISSUE TITLE
struct superblock, log 등에 대한 Device의 ownership

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#223]
`struct Superblock, struct Log` 등은 disk device당 하나씩 가지는 것인데, xv6에서는 1 개의 disk device만 사용된다고 가정하고 struct disk와 별개의 전역 변수로 사용하고 있습니다.

https://github.com/kaist-cp/rv6/blob/672e114f4f6b8642069f6d71659625b8515ed874/kernel/log.c#L49
https://github.com/kaist-cp/rv6/blob/672e114f4f6b8642069f6d71659625b8515ed874/kernel/fs.c#L26-L28

이러한 struct들을 struct Disk 안에 넣는 등의 방법으로 ownership을 명확히 할 필요가 있을지 궁금합니다.

**Comment by efenniht** [comment]
`Superblock` 과 `Log` 둘 다 journalling을 위한 filesystem 의 component 입니다. 따라서 `FileSystem` 이라는 타입을 만들어서 그 안에 집어넣는 게 좋을 것 같습니다.

**Comment by jeehoonkang** [comment]
아직 좀 미진한 부분이 있긴 하지만 FileSystem 안에 둘다 넣었습니다.
