### ISSUE TITLE
struct Inode, DInode의 typ 필드 타입을 enum으로 변경

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#231]
https://github.com/kaist-cp/rv6/blob/0d83d006f070bb770113cd2bc6a56af313b9b012/kernel-rs/src/stat.rs#L1-L8

현재 struct Inode, DInode의 typ 필드는 위와 같이 선언된 `T_DIR, T_FILE, T_DIRECTORY`에 의해 정해집니다.
올바른 추상화를 위해 아래의 FileType처럼 enum으로 변경하려 합니다.
https://github.com/kaist-cp/rv6/blob/0d83d006f070bb770113cd2bc6a56af313b9b012/kernel-rs/src/file.rs#L51-L56

특이사항은 다음과 같습니다.
1. DInode는 `repr(C)`이고, 기존의 `typ` 필드는 `i16`이므로, 새로운 enum에 `#[repr(i16)]`를 사용하려 합니다.
1. 기존의 xv6 코드에서는 `Inode::zeroed()`에서 typ필드는 `T_DIR, T_FILE, T_DIRECTORY` 중 어떤 것에도 포함되지 않는 **0**으로 초기화됩니다. 이를 명확히 하기 위해 `T_NONE = 0`를 선언하려 합니다.
1. Inode 필드와 숫자 0간의 비교 및 혹은 DInode와 Inode 필드 간의 값 이동을 위해 PartialEq와 Copy trait을 derive하려 합니다.

**Comment by efenniht** [comment]
좋은 것 같습니다. Inode 에는 FileType 처럼 해당 type 에서만 의미가 있는 field 가 없나요?

**Comment by kimjungwow** [comment]
> 좋은 것 같습니다. Inode 에는 FileType 처럼 해당 type 에서만 의미가 있는 field 가 없나요?

`major, minor` 필드들은 InodeType::Device 안에 넣겠습니다! :)

**Comment by jeehoonkang** [comment]
이미 리팩토링이 적용된 것 같아 close합니다.  혹시 더 해야할 일이 있었다면 다시 open 부탁드려요 @kimjungwow
