### ISSUE TITLE
Inode 관련 타입 & 메서드는 다른 파일로 옮기기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#233]
그리고 이 타입과 Inode 관련 타입 & 메서드는 다른 파일로 옮기는 것이 좋겠습니다 (다음 PR에서?)

_Originally posted by @efenniht in https://github.com/kaist-cp/rv6/pull/228#discussion_r500042734_

**Comment by kimjungwow** [comment]
@efenniht `fs/path.rs`처럼 `fs/inode.rs`에 Inode 관련 타입 & 메서드를 옮길까요?

**Comment by efenniht** [comment]
네 그렇게 하는 것이 자연스러울 것 같습니다.
