### ISSUE TITLE
printf 할 때 Console lock 을 잡는 문제

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/rv6#243]
원래 xv6 구현은 print lock 과 console lock 이 분리되어 있었는데요, 해당 부분을 리팩토링할 당시에 두 개의 역할이 중복된다고 생각해서 합쳤습니다. 실제로 usertests 를 돌릴 때는 아무런 문제가 발생하지 않으나, Ctrl-P 를 눌러서 process dump 를 보려고 할 때 panic 이 발생합니다. xv6 개발자의 mental model 은 print lock 은 커널의 printf interface 를 synchronize 하는 것이고, console lock 은 user application 이 접근하는 console device 를 보호하는 것 같습니다.

**Comment by jeehoonkang** [comment]
@coolofficials 이거 혹시 해결 부탁드립니다.

**Comment by coolofficials** [comment]
commit https://github.com/kaist-cp/rv6/commit/6fb21dc45bcf203039499ab779804b187a0e7b5f 과 제가 이전에 진행했던 draft pr: https://github.com/kaist-cp/rv6/pull/183/files 을 참고하여 진행할 생각입니다.

**Comment by coolofficials** [comment]
Ctrl-P를 통해 process dump를 보는 것의 panic이 발생하는 원인을 파악 중입니다.
- xv6에서 `printflock`을 disable 했을 때는 booting message 등의 메세지 출력 도중에 코어끼리 서로 switching이 발생하는 현상을 관찰했습니다. (예시: hart hart 1 2 st starting arting)

- struct pr 내부의 locking이 panic signaling을 하는 것 같은데, 정확한 의미를 찾지 못하겠습니다. 문제 파악이 안됩니다.

- console lock을 xv6 상에서 다 없애도 usertests나 process dump, 혹은 기타 다른 부분에서 오류가 관측되지 않습니다.

원인이 fmt::Write을 사용한 구현에 있는 것이라고 추측되어 확인할 생각입니다.

**Comment by coolofficials** [comment]
새로운 이슈 같은데,
`ctrl - P` 를 통한 procdump의 결과가 xv6는 모든 commit에서
```
xv6 kernel is booting

hart 2 starting
hart 1 starting
init: starting sh
$ 
1 sleep  init
2 sleep  sh
```
와 같이 나타납니다.

하지만 rv6의 경우 refactoring을 본격적으로 시작하기 이전인 379cfc51585b6fa55debeeeaa66abcfb3f00e4be 부터 (hart message bug를 해결한 뒤부터는 hart message는 정상적으로 출력되었습니다)
```
xv6 kernel is booting

init: starting sh
$ 
1 panic: acquire
```

**Comment by jeehoonkang** [comment]
@kimjungwow #273 여기서 uart, console 변경한 것으로 보이는데, 혹시 이 이슈와 관련이 있는지 의견 궁금합니다.

**Comment by kimjungwow** [comment]
> @kimjungwow #273 여기서 uart, console 변경한 것으로 보이는데, 혹시 이 이슈와 관련이 있는지 의견 궁금합니다.

https://github.com/kaist-cp/rv6/pull/274/commits/8a23e0fdd2846f56d1c48de163abe5f66c587f9f#diff-ce3c624fd1cc6ba20277c79f63cc1e4d71cb79957bb6f209ce90cba031046ccb upstream 따라잡는 과정에서 이 커밋에서 uart, console을 변경했습니다.

@coolofficials 최근 몇주간의 커밋에서는 아예 ctrl+p가 동작하지 않는 것 같네요.. panicked at 'kerneltrap' 같은 문구도 뜨지 않습니다.. :cry:
