### ISSUE TITLE
Debugging `inode-refactor` branch

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#251]
## @jeehoonkang 교수님, inode-refactor 브랜치 디버깅중  `RcInodeGuard`의 `Deref, DerefMut`에 궁금한 점이 있습니다.

1. `RcInodeGuard`의 `Deref`가 부적절한것 같습니다.

- 예시 1

https://github.com/kaist-cp/rv6/blob/f58dc356b78879c9c339dc90a0c3c5303f1a7cae/kernel-rs/src/fs/path.rs#L145-L148

- 위 코드를 gdb로 확인해보면 `ip` 에 들어있는 InodeInner의 typ값은 1 ( == `T_DIR`) 입니다. 하지만 계속 `Err(())`를 리턴합니다. ( ip.typ는 0으로 나옵니다).
- 아래와 같이 바꿀 경우 정상적으로 동작합니다. ( `riscv` 브랜치의 코드는 부팅 중 위 코드의 147번째 줄에서 `Err(())`를 리턴하는 경우가 없습니다.)

```Rust
if ip.inner.deref().inner.get_mut_unchecked().typ != T_DIR {
```

- 예시 2

https://github.com/kaist-cp/rv6/blob/f58dc356b78879c9c339dc90a0c3c5303f1a7cae/kernel-rs/src/fs/inode.rs#L188-L190

마찬가지로 위 코드의 190번째 줄도 아래와 같이 바꾸면 assert_eq를 정상적으로 통과합니다.

```Rust
assert_eq!(self.inner.deref().inner.get_mut_unchecked().typ, T_DIR, "dirlookup not DIR");
```

2. `RcInodeGuard`의 `DerefMut`는 아래와 같이 `InodeGuard`를 리턴합니다.

https://github.com/kaist-cp/rv6/blob/f58dc356b78879c9c339dc90a0c3c5303f1a7cae/kernel-rs/src/fs/inode.rs#L104-L111

- `RcInode::lock()`에서 아래와 같이 `InodeGuard`인 guard에 대해 `mem::forget(guard)`를 하기 때문에, 위 코드와 같이 DerefMut을 구현하신 것으로 보입니다. 

https://github.com/kaist-cp/rv6/blob/f58dc356b78879c9c339dc90a0c3c5303f1a7cae/kernel-rs/src/fs/inode.rs#L79

- `mem::transmute`를 사용해 `&Inode`를 `InodeGuard`로 바꾸는 경우에도 `RcInodeGuard::DerefMut`가 리턴한 `InodeGuard`가 정상적으로 동작할 수 있는지 궁금합니다. 예를 들면 아래의 코드에서 `&mut RcInodeGuard`인 `ip`가 주어졌을 때, `InodeGuard::read()`를 실행하기 위해 **`RcInodeGuard::deref_mut()`이 실행되는데 여기서 코드가 멈춥니다.** 
- **`RcInodeGuard`가 `InodeGuard`를 들고 있는 것은 안 좋은 구현일까요?**

https://github.com/kaist-cp/rv6/blob/f58dc356b78879c9c339dc90a0c3c5303f1a7cae/kernel-rs/src/fs/mod.rs#L87-L89

**Comment by jeehoonkang** [comment]
@kimjungwow 잘 알아봐주셔서 감사합니다!  저도 말씀하신 곳에 버그가 있는 것 같습니다.

- transmute를 쓰는게 매우 안좋은 일이긴 합니다...
- RcInodeGuard는 (1) reference counter를 하나 들고 있는 동시에 (2) inode lock을 잡은 놈인데, 두 아이디어를 모두 표현하려면 InodeGuard만 가지고 있어서는 안되고 RcInode에 대한 reference를 들고 있어야 합니다.  그래서 이와같이 구현한건데, 그런경우 transmute를 피할 수가 없네요 ㅜ 좀더 고민해보겠습니다...

**Comment by efenniht** [comment]
@jeehoonkang https://github.com/kaist-cp/rv6/tree/inode-refactor-sanguk 이런 식으로 sysfile::create 만 고치면 `RcInodeGuard` 타입은 필요없는 것 같습니다. 어떠신가요?

**Comment by efenniht** [comment]
Close as #253
