### ISSUE TITLE
ProcExecutionGuard

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#258]
#257 이후 proc.rs refactoring 지점입니다.
`myproc` 함수의 구조 때문에 임시로 `struct ProcData`와 `struct Proc`의 field `data`를 `pub`으로 설정했습니다.

`ExecutionGuard`를 만들어 `myproc`을 refactoring 하고 `struct ProcData`와 data를 private으로 다시 변경해야합니다.

**Comment by anemoneflower** [comment]
@anemoneflower

**Comment by coolofficials** [comment]
@anemoneflower FYI: https://github.com/kaist-cp/hafnium-verification/blob/2294e623c1b49644b94cdc2b78335c4e30512e69/hfo2/src/cpu.rs#L318-L364
+ 상욱님의 논문 section 3.4를 참고하시기 바랍니다.

**Comment by anemoneflower** [comment]
오늘 논의한 내용입니다.
- 새로 올려주신 상욱님의 논문 3.4에 자세한 설명이 있습니다.
- struct `Proc`의 `data` field는 현재 실행중인 cpu인 경우에만 접근이 가능하지만, `info` field는 실행중인 cpu가 아니라도 접근해서 값을 수정할 수 있습니다. => 두 field가 lock을 필요로 하는 조건이 다릅니다.
https://github.com/kaist-cp/rv6/blob/a3ab903750af385f1f8a64874ffc979c78e06546/kernel-rs/src/proc.rs#L322-L326
- `data` field를 ProcExcutionguard (현재 코드의 ProcGuard와 비슷)로 감싸고, `info` field의 경우 필요할 때 `Spinlockguard`를 사용하는 방향으로 refactoring을 진행할 예정입니다.
- 이렇게 refactoring 할 경우 `ProcInfo`의 `state: Procstate`가 다른 방식으로 보호되어야 합니다. 하프늄의 리팩토링 로직을 따르면 `ProcData` 안으로 옮기면 되지만, 하프늄과 달리 rv6에는 `ZOMBIE` 와 같은 state가 있어서 `state`를 어떻게 처리할지에 대한 고민이 필요합니다.

**Comment by anemoneflower** [comment]
`ProcExcutionguard` refactoring과 관련한 구체적인 진행계획입니다.

`data`가 `UnsafeCell`로 감싸져 있는 현재의 구조(f5f6a8f)에서는 `Proc.data`에 접근하기 위해서 unsafe한 code가 발생합니다. (line 719)
https://github.com/kaist-cp/rv6/blob/f5f6a8f4ddc3e45a17feeaf529ec7f8f835e993e/kernel-rs/src/proc.rs#L717-L719
`data` field를 명시적인 type으로 표현하기 위해서 현재의 `ProcGuard`와 비슷한 구조로 `ProcExcutionGuard`를 구현해서 `data` field를 감싸는 refactoring을 진행할 계획입니다.
https://github.com/kaist-cp/rv6/blob/f5f6a8f4ddc3e45a17feeaf529ec7f8f835e993e/kernel-rs/src/proc.rs#L332-L345

이 refactoring을 통해 719번줄 같은 코드 대신에 `p.data.pagetable` 과 같이 `data` field에 접근할 수 있게 됩니다.

**Comment by anemoneflower** [comment]
https://github.com/kaist-cp/rv6/pull/315#issue-549975919

- procGuard와 procExcutionGuard의 차이점에 대한 고민이 필요합니다.
