### ISSUE TITLE
upstream 따라잡기

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#261]
mit-pdos에 최신 커밋이 몇개 쌓인 것 같은데, 확인하고 따라잡는게 필요합니다.

**Comment by kimjungwow** [comment]
1. https://github.com/mit-pdos/xv6-riscv/commits/riscv 의 커밋들을 **한 번에** fetch 해 Rust 코드로 따라잡기
2. https://github.com/mit-pdos/xv6-riscv/commits/riscv 의 커밋들을 **한 개씩** fetch -> Rust 코드로 변경하기
어떤 방향이 좋을까요 교수님?

**Comment by jeehoonkang** [comment]
전자를 시도해보고 어려우면 쪼개서 따라갑시다

**Comment by coolofficials** [comment]
확인 결과 rv6에는 https://github.com/mit-pdos/xv6-riscv/commit/9ead904afef8d060c2cc5cee6bd8e8d223de8c40 까지의 commit만 merge되어 있습니다.

**Comment by jeehoonkang** [comment]
@coolofficials C 코드에 반영된 change들이 Rust 코드에도 반영되어 있나요?

**Comment by coolofficials** [comment]
@jeehoonkang  mit-pdos/xv6-riscv@9ead904 까지를 말씀하시는거면 교수님께서 C2Rust transpile commit 7037bf89046e626ff1a50240cdbd5afcab260419 적용을 해당 commit 이후에 적용하신 것으로 보입니다.

**Comment by coolofficials** [comment]
https://github.com/kaist-cp/rv6/issues/261#issuecomment-722331537

2번의 방법으로 #262 를 진행해봤습니다.
제 생각에는 1번의 방법으로 전체를 fetch 하되, 수정사항 반영은 https://github.com/mit-pdos/xv6-riscv/commits/riscv 의 commit을 하나하나 따라가면서 check 하는 것이 안전할 것 같습니다.

전체를 fetch 하는 것은 rebase의 편의성을 위함이고,
하나하나 따라가면서 check 하는 것은 잡다한 수정사항이 너무 많아 한 번에 확인하기 어렵기 때문입니다.

**Comment by kimjungwow** [comment]
@coolofficials 이 곳에서 이어서 논의하겠습니다. 

제가 https://github.com/kaist-cp/rv6/pull/262#issuecomment-722872545 에서 말씀드린 방식 (**수정된 xv6 코드를 rv6 밑에 까는 방식**)으로 rebase를 하면, 저희가 여름 방학에 merge한 conflict들이 다시 나와서 시간이 오래 걸릴 것으로 보입니다.
따라서 **수정된 xv6 코드의 밑에 rv6 코드를 까는 방식**으로 rebase를 하면 conflict가 적게 발생해 rebase가 쉬울 것으로 보입니다 (Rust 코드에서는 conflict가 발생하지 않아야 합니다. ~제발..~)
- git rebase의 `interactive` 옵션을 사용하면 여러 커밋들을 묶어서 rebase 할 수 있습니다. 같은 PR의 commit들을 묶어서 rebase하면 불필요한 conflict 해결하는 노력을 줄일 수 있어보입니다.
- 아래와 같은 방식으로 **rv6 코드의 위에 수정된 xv6 코드를 둘 수 있습니다**
```
git clone git@github.com:mit-pdos/xv6-riscv.git issue261
cd issue261
git add remote upstream git@github.com:coolofficials/rv6.git
git fetch upstream riscv
git rebase upstream/riscv
```

**Comment by coolofficials** [comment]
https://github.com/kaist-cp/rv6/issues/261#issuecomment-722936005

요는 update된 상태의 xv6에 저희가 쌓아올린 rv6 commit들을 쌓는다는 말씀이시죠? 좋은 것 같습니다.

**Comment by kimjungwow** [comment]
@coolofficials 제가 https://github.com/kaist-cp/rv6/issues/261#issuecomment-722936005 에서 제안한 방향은 아래와 같습니다.. ㅎㅎ
![Imgur](https://imgur.com/at9TZw3.png)

**Comment by coolofficials** [comment]
> @coolofficials 제가 [#261 (comment)](https://github.com/kaist-cp/rv6/issues/261#issuecomment-722936005) 에서 제안한 방향은 아래와 같습니다.. ㅎㅎ
> ![Imgur](https://camo.githubusercontent.com/f96459318391ed7351b7103b9e8ee25c56de54b3c790d66669e5b7007973849d/68747470733a2f2f696d6775722e636f6d2f617439545a77332e706e67)

아 어제 재황님과 식사하면서 이해했습니다. 근데 혹시 급하신거면 다른 분이 하셔도 좋을 것 같습니다.

**Comment by kimjungwow** [comment]
@coolofficials 시원님께서 핀토스 끝내고 맡아주시면 될 것 같습니다! :)

**Comment by jeehoonkang** [comment]
위와 같이 하면 mit-pdos의 커밋을 그대로 가져오는게 아니게 됩니다.  그냥 rebase하지 말고 merge하는게 좋겠습니다.

**Comment by kimjungwow** [comment]
merge할 때 `kernel` 디렉토리 안의 `.c, .h` 파일들은 항상 `mit-pdos`의 코드를 기준으로 삼아도 될까요?
예를 들면, `kernel/fs.h`의 `struct dinoe:major, minor`는 rv6에서 **ushort**이지만 (https://github.com/kaist-cp/rv6/commit/746610a5d1796014258e32ff7288ee4dd6965925에서 변경) mit-pdos에서는 **short**입니다.

**Comment by jeehoonkang** [comment]
@kimjungwow 아 이게 우리가 필요해서 바꾼 것 같은데...  일단 mit-pdos 버전으로 되돌리기로 할까요?  아니면 우리의 의도를 살려서 short로 해도 될 것 같긴 합니다.  정우님이 판단 부탁드려요.
