### ISSUE TITLE
arena에서 linked list 추상화

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#265]
Hafnium에서 했던 것처럼 intrusive linked list를 추상화하고 그걸 사용하면 어떨가 합니다: https://github.com/kaist-cp/hafnium-verification/blob/hfo2/hfo2/src/list.rs

**Comment by coolofficials** [comment]
이 이슈가 현재 arena.rs에 이미 구현된 intrusive linked list 관련 api들을 list.rs로 분리하여 추상화해서 사용하자는 말씀이신거죠?
이 경우 arena.rs에 필요한 method들만 우선적으로 구현하면 되나요?
