### ISSUE TITLE
kernel() 등 global function 사용 지양

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#267]
kernel() 등 global function은 되도록 적은 곳에서만 부르도록 리팩토링해야 합니다.  Kernel object abstraction을 확립하기 위한 방안입니다.

**Comment by Medowhill** [comment]
이제 많은 부분이 리팩토링되었기 때문에 `kernel()`을 줄이는 문제를 본격적으로 고민할 때인 것 같습니다. `CurrentProc`을 `usertrap`에서 만들어서 계속 인자로 전달한 것처럼, `Kernel`도 `usertrap`에서 만든 뒤 계속 인자로 전달함으로써 대부분의 `kernel()`을 없앨 수 있을 것 같은데, 이 방법에 대해 어떻게 생각하시나요? 또한, `kernel()`은 커널 초기화 중에 호출되지 않을 것을 가정하기 때문에 unsafe 함수가 되어야 올바른 것 같습니다.

**Comment by coolofficials** [comment]
@Medowhill @travis1829 sync up에서 말씀드렸던 관련 논의의 링크입니다. https://github.com/kaist-cp/rv6/pull/302#discussion_r539108831

**Comment by Medowhill** [comment]
#290 과 #539 로 분리.
