### ISSUE TITLE
Potential bug in xv6 (mit-pdos)?

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#280]
- C 구현에서 다음과 같이 함수들이 불리는데: sys_read -> fileread -> readi -> bmap -> balloc -> log_write
- log_write 하기 전에 begin_op이 불리지 않는 것 같습니다.

**Comment by jeehoonkang** [comment]
https://github.com/mit-pdos/xv6-riscv/issues/49

**Comment by coolofficials** [comment]
제가 이슈를 정확히 이해하지 못한 것 같습니다. sys_read가 transaction 내부에서 일어나야 하기 때문에 begin_op가 불려야 하는데 begin_op가 없이도 sys_read가 불리는 bug인가요?

**Comment by jeehoonkang** [comment]
sys_read 안에서 begin_op을 먼저 하고 log_write을 불러야 하는데 그렇지 않다는게 버그의 핵심입니다.

**Comment by jeehoonkang** [comment]
- @efenniht 님이 버그가 아님을 밝혔습니다.
- 상욱님, paper의 working draft에, 이거 상욱님이 잘 리팩토링해서 버그 없음을 코드에 드러냈다고 적어주세요.  그리고 이 이슈 close 해주세요.

**Comment by efenniht** [comment]
일단 paper 에 추가했습니만, 이것에 대해 이야기하려면 filesystem 의 invariant 에 대한 이야기를 먼저 해야할 것 같습니다...
