### ISSUE TITLE
begin_op on syscall handling

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#284]
`begin_op`의 comment에 보면 `/// Called at the start of each FS system call.`
이라는 내용이 있어서 system call을 handling 할 때 `begin_op`를 부르는 방향성에 대해 논의했습니다.

_Originally posted by @coolofficials in https://github.com/kaist-cp/rv6/issues/279#issuecomment-731177360_

**Comment by jeehoonkang** [comment]
원래 코드의 의도는 좀더 fine-grained하게 필요할때만 begin_op을 부르는 것 같습니다.  저는 그 의도를 보존해야한다고 생각합니다.
