### ISSUE TITLE
Ownership of UartCtrlRegs to UART?

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#287]
`struct Uart`가 `UartCtrlReg`에 대한 소유권을 갖도록 수정하는 것이 옳을지 논의가 필요합니다.

_Originally posted by @coolofficials in https://github.com/kaist-cp/rv6/pull/286#discussion_r528344388_

**Comment by coolofficials** [comment]
@efenniht 님께서 두 struct를 분리하는 것이 옳다고 말씀하셨던 것으로 기억합니다.
제가 생각하기에는 `UartCtrlRegs`는 하드웨어의 추상화고 `Uart`는 register와 interact 하기 위한 interface의 추상화입니다.
상욱 님도 이러한 맥락에서 분리하는 것이 옳다고 하셨던 것 같습니다.

**Comment by kimjungwow** [comment]
`UartCtrlRegs`와 `Uart`를 분리한다는 것은 서로 다른 파일에 두고, `Uart::init()`을 `UartCtrlRegs::init()`으로 바꾸는 건가요? 😃

**Comment by coolofficials** [comment]
> `UartCtrlRegs`와 `Uart`를 분리한다는 것은 서로 다른 파일에 두고, `Uart::init()`을 `UartCtrlRegs::init()`으로 바꾸는 건가요? 😃

아닙니다. 현재 Uart가 UartCrrlRegs를 field로 가지지 않지만 Uart Registry에 수정을 가하고 있기 때문에 Uart의 field로 controller: UartCtrlRegs 등으로 포함시키는 것에 대한 논의입니다. Init과 putc_sync를 참고하시면 될 것 같습니다.

**Comment by kimjungwow** [comment]
상욱님 말씀은 수정하지 않고 현 상태를 유지하는 것이 좋다는 말씀이셨군요!!

**Comment by coolofficials** [comment]
> 상욱님 말씀은 수정하지 않고 현 상태를 유지하는 것이 좋다는 말씀이셨군요!!

분명하지는 않습니다. 다른 비슷한 object(hardware와 연관된)에 관한 논의일 수도 있습니다...
