### ISSUE TITLE
ProcessSystem::alloc(), proc_pagetable()에서 destructor/drop을 적절히 사용하도록 리팩토링

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#295]
### #291 에서 upstream을 반영하던 중, `proc.rs`에서 destructor/drop을 사용하도록 리팩토링할 부분을 찾았습니다.

리팩토링이 필요한 부분과, 어떻게 리팩토링할지 제 생각을 적어보았습니다. 시간이 있으시다면 @coolofficials 시원님과 @anemoneflower 서윤님께서도 의견을 주시면 감사하겠습니다!

#### 1. `ProcessSystem::alloc()`에서 `proc_pagetable()`이 Err를 리턴하는 경우

https://github.com/kaist-cp/rv6/blob/1d14b5ad386cc9eedb55a53d779155c951884413/kernel-rs/src/proc.rs#L583-L587

  - **freeproc()과 관련해 어떻게 destructor/drop을 적절히 사용할 지 고민해보면 좋겠습니다!**
    - `ProcGuard`를 drop할 때마다 `freeproc()`이 실행되는 것은 옳지 않다고 생각합니다.

-------------------------------------

#### 2. `proc_pagetable()`에서 `mappages()`가 Err를 리턴하는 경우

https://github.com/kaist-cp/rv6/blob/1d14b5ad386cc9eedb55a53d779155c951884413/kernel-rs/src/proc.rs#L907-L933

  - **`PageTable<A>::drop()`을 만들면 좋겠습니다.** 
    - `PageTable<A>::drop()`이 `uvmfree(sz)`를 호출 하면 어떨까요? 
      - 이를 위해 `ProcData`의 `sz`를 `ProcData.pagetable` 안으로 옮기면 좋겠습니다. (`ProcData.sz`는 Size of process memory (bytes)를 의미합니다) 
    - xv6의 의도 보존을 위해 `uvmfree()`는 `vm.rs`에 계속 두면 좋겠습니다.

**Comment by anemoneflower** [comment]
> * `ProcData`의 `sz`를 `ProcData.pagetable` 안으로 옮기면 좋겠습니다. (`ProcData.sz`는 Size of process memory (bytes)를 의미합니다)

확인이 늦었습니다..ㅎㅎ `ProcData.pagetable` 안으로 옮긴다는 것은 `PageTable struct`에 sz를 추가하자는 말씀이시죠? `PageTable struct`가 `Kernel`에서도 사용되는데 `Kernel`이 사용하지 않는 값을 `PageTable struct`에 추가하는 것이 괜찮을지 궁금합니다. (저도 고민해보겠습니다!)
https://github.com/kaist-cp/rv6/blob/9999d37267ac07e0feb6ffd12e58ab48d9f1f85b/kernel-rs/src/kernel.rs#L36-L45

**Comment by coolofficials** [comment]
1번 이슈 의미를 정확히 파악하기 힘든데,
"freeproc()에서만 Procstate를 UNUSED로 바꾸며, 다른 필드들에는 ptr::null_mut()등 빈 값을 넣기 때문에"
이 부분이 Procstate를 unused로 변경하는 곳이 freeproc 뿐이라는 의미인가요 아니면 바꿀 때 빈 값을 안 넣는 field가 Procstate 뿐이라는건가요?

**Comment by kimjungwow** [comment]
* "freeproc()에서만 Procstate를 UNUSED로 바꾸며, 다른 필드들에는 ptr::null_mut()등 빈 값을 넣기 때문에"

-> Procstate를 UNUSED로 변경하는 곳이 `freeproc()` 뿐이고, `freeproc()`에서 `ProcInfo::state` 외에 ProcInfo의 다른 필드들에는 `ptr::null_mut()` 등 빈 값(초기값?)을 넣는다는 의미였습니다! @coolofficials 

지금 보니 `proc.rs::wait()` 내에서는 procstate가 ZOMBIE인 경우에도 `freeproc()`이 실행되는 등, Procstate가 UNUSED인 경우에만 `freeproc()`이 실행되는 것이 아니네요.. 
이 이슈는 https://github.com/kaist-cp/rv6/pull/291#discussion_r530370480 에서 나온 이야기인데, `freeproc()`과 관련해 어떻게 destructor/drop을 적절히 사용할 지 고민해보면 좋겠습니다!

**Comment by coolofficials** [comment]
2번은 조금 조심스러울 필요가 있을 것 같은데, 만나서 논의하는게 좋을 것 같습니다.

- Pagetable의 size는 memory 단위라기보다는 Page 단위로 PTE_PER_PT입니다.
- Pagetable에 allocate 된 memory의 size를 field로 넣는다면 page aligned(round-up) 되도록 하는게 의미론적으로 맞는 것 같습니다.
- ProcData의 sz가 항상 page_aligned 된 상태로 사용되지는 않는 것 같습니다 (Process Growth). 
- 차라리 ProcData의 sz는 그대로 둔 채로, allocate 된 page의 갯수를 Pagetable의 field로 넣어 counting하도록 하고, 관련해서 alignment 방식과 sz를 인자로 받는 method들을 refactoring 하는 것이 좋을 것 같습니다.

**Comment by jeehoonkang** [comment]
@travis1829 @Medowhill 재민님, #334 에서 이 이슈를 다루고 있나요? 태우님이 이 이슈를 보고 있다고 하셨는데 혹시 중복된 작업인지 알고싶어서 질문드립니다.

**Comment by travis1829** [comment]
일단 저는 재민님께서 하고 계신게 끝나기를 기다리면서, WaitChannel 관련된 걸 먼저 보고있었습니다!
(다만, 내용을 보니 딱히 그렇게 겹치지는 않는 것 같습니다!)

**Comment by Medowhill** [comment]
이 이슈를 직접적으로 다루고 있지는 않습니다. 다만 #330 과 #334 가 수정한 부분이 꽤 겹쳐서 둘 중 하나를 먼저 merge 하면 다른 하나에 꽤 conflict가 생길 것 같습니다. (제가 기존 PR을 잘 확인하고 일을 시작했어야 했는데 제목을 대충 보고 `Proc`에만 관련되고 VM과는 상관없는 줄 알았습니다. 죄송합니다. 앞으로는 이미 열린 PR를 잘 확인해서 conflict가 많이 발생하는 경우가 없도록 하겠습니다.)

#267 에서 언급한 것처럼 `kernel()`을 줄이는 방향으로 리팩토링해야 하고, 이를 위해서 추후에는 `PageTable` 할당이 해제될 때 인자로 `Kmem`을 받아서 해당 메모리 풀에 페이지를 직접 돌려 주도록 수정할 생각을 하고 있었습니다. (#334 에서는 다루고 있지는 않습니다.) `Kmem`을 인자로 받으려면, `drop` 구현을 통해 자동으로 `PageTable`이 drop되게 만들기는 어려울 것 같습니다.

**Comment by travis1829** [comment]
`sz`필드 에대해선 일단, 오늘 교수님과 미팅한 결과, `sz` 필드는 다시 `ProcData`로 옮기는 걸로 결정했습니다!

그리고, `PageTable::Drop`의 경우, 현재의 proc.rs의 `freewalk()`에서와 비슷하게, 그냥 직접 recursive하게 `PageTable`을 탐색하면서 leaf page들을 직접 `kernel().free()`할 계획입니다. (이렇게 하면 굳이 Kernel와 User의 PageTable을 구분할 필요가 적어집니다)
다만, 이 부분은 앞으로 바뀔 부분이 많고, 또 홍재민님께서 말씀하신 대로 `Kmem`을 받도록 수정하려면 어차피 나중에 또 바뀌게 될 것 같습니다.

**Comment by jeehoonkang** [comment]
ping for notifying zulip
