### ISSUE TITLE
proc.c : global lock인 proc_tree_lock로 proc 내부의 parent 필드를 잘 보호하기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#300]
#### xv6에서 `proc.parent`를 변경할 때는 `proc.lock`이 아닌 global lock인 `struct spinlock proc_tree_lock`를 잡고 변경하도록 수정되었습니다. 

https://github.com/mit-pdos/xv6-riscv/commit/8d4fbc6e2a4c8373453f2e1380bb8c6ca8d334c0

`struct proc` 내부의 `parent` 필드를 보호하는 lock이 `struct proc` 외부에 있는 `struct spinlock proc_tree_lock`으로 변경되었습니다. 이를 어떻게 해결할지 고민해야 합니다.

아래는 교수님의 코멘트들입니다.
- 이 문제는 lock과 lock이 보호해야 하는 것이 decoupled된 경우이다. ExecutionGuard도 decoupled된 경우였지만, 이 이슈가 더 decoupled의 정도가 크다.
- `struct proc` 내부의 `parent`를 외부로 빼면 어떨까?
  - `parent`를 외부로 빼서, **tree 형태**로 proc들의 parent/child 관계를 표현하는 것은 (좋은 포인트이지만) **안 하는 것이 좋겠다**. rv6에서 tree는 이 경우에만 쓰일 것이어서, generalize하는데 노력이 많이 필요할 것 같다.

**Comment by coolofficials** [comment]
확인을 위해서
"parent를 외부로 빼서, tree 형태로 proc들의 parent/child 관계를 표현하는 것은 (좋은 포인트이지만) 안 하는 것이 좋겠다. rv6에서 tree는 이 경우에만 쓰일 것이어서, generalize하는데 노력이 많이 필요할 것 같다."

이 말씀은 해당 structure를 만드는 것이 바람직한 방법이지만, cost가 많이 들어서 우선순위화에서 밀리고, 용례가 유일하니 다른 쉬운 방법을 찾자는 말씀이신거죠?

**Comment by kimjungwow** [comment]
> 확인을 위해서
> "parent를 외부로 빼서, tree 형태로 proc들의 parent/child 관계를 표현하는 것은 (좋은 포인트이지만) 안 하는 것이 좋겠다. rv6에서 tree는 이 경우에만 쓰일 것이어서, generalize하는데 노력이 많이 필요할 것 같다."
> 
> 이 말씀은 해당 structure를 만드는 것이 바람직한 방법이지만, cost가 많이 들어서 우선순위화에서 밀리고, 용례가 유일하니 다른 쉬운 방법을 찾자는 말씀이신거죠?

그렇습니다! 👍

**Comment by kimjungwow** [comment]
Map (proc.pid -> proc.parent `* Proc` 형태로 proc.parent를 보호하면 어떨까요? 
비록 Map 내에서 iterate하며 현재의 `Proc`을 찾은 뒤에야 parent를 접근해야 하는 것이 찜찜하지만, `proc_tree_lock`이 보호하는 것을 깔끔하게 드러낼 수 있습니다. 
xv6에서 `struct buf`에 `prev, next` 필드가 있는데, rv6에서는 `MruArena`로 바꾼 것도 같은 맥락이라고 생각합니다.

**Comment by travis1829** [comment]
* proc.parent만을 저장하기 위한 간단한 wrapper을 새로 만들면 어떨까요?
* proc.parent를 write하고 싶으면 wrapper의 API를 써야하고, 이 API가 global lock을 요구하게 하면 (또는 내부에서 acquire하면) 될 것 같습니다.
* 새로운 type을 만드는게 좀 낭비같긴 하지만 Map을 쓰는 것보다는 runtime 비용이 적을 것 같습니다.
