### ISSUE TITLE
CI 설정 문제

### ISSUE THREAD

**Issue by coolofficials** [kaist-cp/rv6#303]
현재 CI 설정에 문제가 있는 것 같습니다.
PR #302 fail
현재 riscv branch도 fail 상태로 표기됩니다.

**Comment by kimjungwow** [comment]
- 아래와 같은 두 증상이 주로 나타납니다.
  - CI에서 오랜 시간 pending 상태에서 넘어가지 않음
  - twochildren usertest에서 10분 이상 output이 나오지 않아 fail처리됨
- 로컬에서는 잘 통과해도 이런 증상이 나타납니다.
- travis CI에 로그인 한 후 restart build를 반복하다보면 통과합니다.

**Comment by efenniht** [comment]
CI 문제 확인해 봤는데 riscv 브랜치가 로컬에서도 가끔씩 twochildren 테스트에서 타임아웃이 납니다. 제 생각에 최근 PR 에서 data race 같은 게 생긴 것 같습니다. 상대적으로 CI 환경이 더 느려서 data race 가 더 자주 발생하는 것 같은데 어디가 문제인지 확인 부탁드립니다...

**Comment by efenniht** [comment]
https://travis-ci.community/t/builds-hang-in-queued-state/10250 travis-ci.com 으로 옮기면 대기시간이 짧아질 수 있다고 합니다.

**Comment by jeehoonkang** [comment]
가능하면 유료 서비스보다는 연구실 내 jenkins로 옮기고자 합니다.
