### ISSUE TITLE
Linker warning: "cannot find entry symbol _entry"

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#305]
아래와 같이 linker에서 warning이 나긴 합니다만, 실행이 잘 되긴 합니다.

```
riscv64-linux-gnu-ld -z max-page-size=4096 -T kernel/kernel.ld -o kernel/kernel kernel/entry.o kernel/swtch.o kernel/trampoline.o kernel/kernelvec.o kernel-rs/target/riscv64gc-unknown-none-elfhf/release/librv6_kernel.a 
riscv64-linux-gnu-ld: warning: cannot find entry symbol _entry; defaulting to 0000000080000000
riscv64-linux-gnu-objdump -S kernel/kernel > kernel/kernel.asm
riscv64-linux-gnu-objdump -t kernel/kernel | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$/d' > kernel/kernel.sym
qemu-system-riscv64 -machine virt -bios none -kernel kernel/kernel -m 128M -smp 3 -nographic -drive file=fs.img,if=none,format=raw,id=x0 -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0

rv6 kernel is booting
```

- xv6에서도 그런지 궁금합니다.
- 의도한건지, 아니면 의도는 아니지만 어떻게 잘 동작하는건지 궁금합니다.

**Comment by coolofficials** [comment]
```
riscv64-linux-gnu-ld: warning: cannot find entry symbol _entry; defaulting to 0000000080000000
riscv64-linux-gnu-objdump -S kernel/kernel > kernel/kernel.asm
riscv64-linux-gnu-objdump -t kernel/kernel | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$/d' > kernel/kernel.sym
gcc -Werror -Wall -I. -o mkfs/mkfs mkfs/mkfs.c
```

교수님 xv6에서도 똑같이 발생함은 확인됩니다.

**Comment by kimjungwow** [comment]
### Linker warning 없애기 : `entry.S`에서 `_entry`를 글로벌로 선언해야 warning이 뜨지 않습니다.

- kernel.ld에서는 아래와 같이 starting point of xv6를 `_entry`로 설정합니다.

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel/kernel.ld#L2

- 하지만 `_entry`는 `globl`로 설정되어 있지 않아서 ` warning: cannot find entry symbol _entry` warning이 발생합니다.  **`entry.S`의 L5와 L6 사이에 `.globl _entry`를 넣으면 해결됩니다.**

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel/entry.S#L5-L6

- `kernel.ld`에서 아래와 같이 설정했기 때문에 `defaulting to 0000000080000000`가 나옵니다. `_entry`를 찾지 못했기 때문에, `kernel.ld`에서 지정한 `0000000080000000`를 starting point of xv6로 설정하는 것으로 보입니다.
  - 예를 들어 `kernel.ld`의 L10을 `. = 0x80001000;`로 바꾸면, `riscv64-linux-gnu-ld: warning: cannot find entry symbol _entry; defaulting to 0000000080001000`라는 경고가 나옵니다.

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel/kernel.ld#L6-L10

### 의도는 아니었지만 잘 동작한 이유?

- xv6의 Makefile에서는 `entry.o`를 `OBJS`에 가장 먼저 포함시킵니다. `kernel.ld`의 10번째 줄에서 `. = 0x80000000;`라고 했기 때문에, _entry의 주소는 가장 첫 주소인 `0x80000000`가 됩니다.
  - `OBJS`의 순서를 바꾸면 xv6가 부팅이 되지 않는 것도 같은 맥락이라고 생각합니다.
  - 예 : `OBJS = $K/start.o $K/entry.o ...`로 하면, `_entry`의 주소가 `0x80000000`이 아니게 되며, 부팅이 되지 않습니다.

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/Makefile#L16-L17

![Imgur](https://imgur.com/bIOyTIH.png)

- 따라서 `kernel.ld`에서 `ENTRY( _entry )`를 지우기만 해도 xv6는 정상 동작하며, linker warning도 뜨지 않습니다. 하지만 `entry.S`에 `.globl _entry`를 추가하는 것이 xv6의 의도에 더 맞다고 생각합니다.

**Comment by coolofficials** [comment]
Xv6에도 report 하는 것이 좋을까요?

**Comment by kimjungwow** [comment]
넵 xv6에 report 했습니다!

**Comment by coolofficials** [comment]
https://github.com/mit-pdos/xv6-riscv/pull/28#issue-489362944 이미 있었군요..!
