### ISSUE TITLE
global variable 선언 시 Maybeuninit을 사용할지 고민하기

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/rv6#308]
global variable에서 Maybeuninit을 사용할지 고민해야 합니다

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel-rs/src/kernel.rs#L27-L29

https://github.com/kaist-cp/rv6/blob/d28972066b059796b1ebb80afccd3407cdcb4c01/kernel-rs/src/start.rs#L26-L27

**Comment by Medowhill** [comment]
#424 에서 관련 논의 진행 중이며, `MaybeUninit`은 사용하지 않을 것 같습니다.
