### ISSUE TITLE
Unsound API SpinlockProtected::get_mut

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/rv6#324]
`SpinlockProtected::get_mut` 코드는 다음과 같은 unsoundness 를 가지고 있습니다.

 1. `guard` 의 shared reference 로 underlying data 의 mutable reference 를 가져올 수 있으므로 mutable reference 가 alias 할 수 있습니다. (`clippy::mut_from_ref` 가 해당 내용을 경고하는 lint입니다)
 2. 리턴하는 reference 의 lifetime 이 `self` 의 lifetime 에 bound하지 않으므로 `self` 가 move되고 나서도 reference가 살아있을 수 있습니다. 예를 들어 다음과 같습니다.
```rust
static LOCK: RawSpinlock = RawSpinlock::new("test");

fn test() {
    let v = SpinlockProtected::<i32>::new(&LOCK, 0);
    let mut guard = v.lock();
    
    let w_mut = {
        let w = SpinlockProtected::<i32>::new(&LOCK, 1);
        w.get_mut(&mut guard)
    };

    *w_mut = 2;
}
```

_Originally posted by @efenniht in https://github.com/kaist-cp/rv6/pull/318#discussion_r555225581_

**Comment by travis1829** [comment]
제일 처음처럼 기존의 guard를 consume해서 다른 guard를 만들어내는 방식으로 다시 바꾸는게 좋을까요?
https://github.com/kaist-cp/rv6/blob/c50a2d8c52a7932bd56a0d01ede5b8e1cb09ee89/kernel-rs/src/spinlock.rs
(이때는 내부 data를 access하려면 guard를 deref하는 방법밖에 없습니다)
(참고: GlobalSpinlock::get_mut는 임시로 놔둔 거라서 없애야 됩니다)

일단 2번 자체는 self에도 lifetime을 붙이면 막히는 것 같긴 한데 1번이 문제인 것 같네요.

**Comment by efenniht** [comment]
1번은 인자 guard 의 타입을 mutable reference 로 바꾸면 될 것 같은데 그러면 다른 문제가 생기나요?

**Comment by travis1829** [comment]
지금 그렇게 해보고 있었습니다! 일단 더 이상 다음과 같은 예는 안 되는 것 같습니다.
```
fn test() {
    let v = SpinlockProtected::<i32>::new(&LOCK, 0);
    let mut guard = v.lock();

    let w1 = v.get_mut(&mut guard);
    let w2 = v.get_mut(&mut guard);

    *w1 = 10;
    *w2 = 20;
}
```
일단 조금 더 확인해보고 변경사항 말씀드리겠습니다.

**Comment by jeehoonkang** [comment]
@travis1829 저는 가능하면 lock_with_guard처럼 guard가 옮겨다니지 않는 design을 선호합니다.
혹시 spinlock protected에 접근할땐 spinlock protected의 &mut을 필요로 하되, spinlock guard의 & (shared reference) 를 받도록 디자인할 수도 있을까요?  그럼 혹시 상욱님이 말한 soundness 문제가 해결되는지 궁금합니다.

**Comment by travis1829** [comment]
확인해보겠습니다!
