### ISSUE TITLE
Syscall 함수들의 input parameter?

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#332]
system call 함수들에 input parameter를 사용하면 좋을 것 같습니다. 예시로, `sys_chdir`에서 `dirname`을 받도록 수정할 수 있습니다.
https://github.com/kaist-cp/rv6/blob/95a44ad319995d7f1f28b23874d56f76087cce0d/kernel-rs/src/sysfile.rs#L296-L302
```rust
    pub unsafe fn sys_chdir(&self, dirname: &Path) -> usize {
        let p: *mut Proc = myproc();
        let mut data = &mut *(*p).data.get();
        let tx = self.file_system.begin_transaction();
        let ptr = ok_or!(dirname.namei(&tx), return usize::MAX);
```
이렇게 수정하면 다음과 같은 장점이 있습니다.
1. 목적을 더 확실하게 표현할 수 있다
2. `argstr`이 unsafe하기 때문에 syscall 함수 내부의 unsafe가 줄어든다.

---

- xv6의 의도에 어긋나지 않는지
- sysfile.rs refactoring도 현재 우선순위에 포함되는지

궁금합니다.

**Comment by jeehoonkang** [comment]
반대합니다. 왜냐하면 `sys_*` 함수의 signature가 모두 같은게 xv6의 의도인 것 같아서요: https://github.com/kaist-cp/rv6/blob/f5f6a8f4ddc3e45a17feeaf529ec7f8f835e993e/kernel-rs/src/syscall.rs#L76 https://github.com/kaist-cp/rv6/blob/cb68dbc2d32a3975cfbffcdf4c15993139cead80/kernel/syscall.c#L108

arg lookup이 sys_* 안에서 일어나는게 의도인 것 같습니다.

**Comment by coolofficials** [comment]
Parameter는 쓰지 않더라도 arg lookup을 해주는 helper function을 사용하는 것은 어떤가요? 반복적인 패턴이 너무 많은 것 같다는 생각이 듭니다.

**Comment by jeehoonkang** [comment]
@coolofficials 혹시 좀더 구체적인 제안을 해주실 수 있을까요?

**Comment by coolofficials** [comment]
제 의견은 `argfd`처럼 `argpath`를 만들어서 사용하는 것이 어떨까 하는 것이었습니다.
error handling의 반복적인 패턴을 잘 담을 수 있는 방법을 생각해보겠습니다.

**Comment by efenniht** [comment]
좀 타협해서 이런 식으로 하는 게 어떨까요:
 - `syscalls` array list 에 들어가는 함수들은 지금 함수 signature 를 유지하고,
 - `sys_*` 함수들이 argument 를 fetch해서 여러 인자를 받는 함수를 받는 함수를 call 하는 게 어떨까요: e.g. `open(&self, name: &Path, omode: usize) -> Result<usize, ()>`
 - 이는 `arg*` 류의 함수가 `sys_*` 류 함수의 주요 unsafe인 것 같아서 그렇습니다. 그래서 unsafe fn 에서 safe 한 portion 을 떼어내는 refactoring 으로 unsafe SLOC 을 줄일 수 있어 보입니다.

**Comment by anemoneflower** [comment]
좋은 방향이라고 생각합니다!
