### ISSUE TITLE
Using unsafe in unsafe functions

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#335]
현재는 `unsafe` 함수 안에서 `unsafe` 블록 없이 `unsafe`한 일들을 할 수 있지만 이는 바람직하지 않습니다. (<https://github.com/rust-lang/rfcs/blob/master/text/2585-unsafe-block-in-unsafe-fn.md>) 이는 `#[deny(unsafe_op_in_unsafe_fn)]`를 함수나 모듈 앞에 추가해 해결할 수 있습니다. (<https://github.com/rust-lang/rust/pull/72709>)

PR #334 에서 해당 기능을 사용할 수 있도록 `lib.rs`에 `#![feature(unsafe_block_in_unsafe_fn)]`를 추가했고 PR에서 수정한 함수 하나가 `#[deny(unsafe_op_in_unsafe_fn)]`를 사용하고 있습니다. 현재 단계에서는 해당 기능이 당장 중요하지 않지만, 리팩토링이 마무리 단계에 들어가고 본격적으로 `unsafe`에 대한 논증을 하게 되면 해당 기능을 프로젝트 전체에서 사용하는 것을 고려해 보아야 할 거 같습니다.

**Comment by jeehoonkang** [comment]
매우 좋은 것 같습니다. 이런 기능이 있는지 몰랐는데 우리 목적으로는 지금 빨리 켜는게 좋을 것 같습니다.

**Comment by Medowhill** [comment]
이걸 혹시 code base 전체에 적용할 수도 있을까요?

_Originally posted by @jeehoonkang in https://github.com/kaist-cp/rv6/pull/334#discussion_r558818054_

네. `lib.rs`에 `#![deny(unsafe_op_in_unsafe_fn)]`를 추가하면 프로젝트 전체에 적용할 수 있습니다. 그러나 지금 바로 적용하면 상당히 많은 unsafe 함수에서 컴파일 오류가 발생할 것이기 때문에, 일단은 그렇게 하지 않았습니다. 일단은 리팩토링 과정에서 파일 단위로 해당 어트리뷰트를 추가하고, 나중에 대부분의 파일에 해당 어트리뷰트가 적용되면 그때 프로젝트 전체에 적용하는 것은 어떻게 생각하시나요? 이 문제는 #335 에서 이야기하는 것이 더 좋을 것 같습니다.

_Originally posted by @Medowhill in https://github.com/kaist-cp/rv6/pull/334#discussion_r559332601_
