### ISSUE TITLE
sysfile.rs의 pipe refactoring

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#337]
```
        let mut fd0 = pipereader.fdalloc().map_err(|_| ())?;
        let mut fd1 = pipewriter
            .fdalloc()
            .map_err(|_| data.open_files[fd0 as usize] = None)?;

```
현재 코드는 일단 data에 써놓고 bail out 하는 경우 되돌리는 패턴입니다. 혹시 더 refactoring할 수 있을 여지가 있을지 고민해보아야 합니다.

_Originally posted by @jeehoonkang in https://github.com/kaist-cp/rv6/pull/333#discussion_r558296169_

**Comment by coolofficials** [comment]
논의 결과 @jeehoonkang 현재 상태로 두는 것이 xv6와 다르지 않고 딱히 refactoring을 할 여지(필요성)가 없다고 판단되었습니다. 일단 Won't fix 로 마킹하겠습니다. 교수님께서 판단해주시면 감사하겠습니다.
