### ISSUE TITLE
PTE_R, PTE_W, PTE_X 타입

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#341]
https://github.com/kaist-cp/rv6/blob/059931901346c8634f3b61cf1e0242d88ea3f8bf/kernel-rs/src/riscv.rs#L352-L356

`PTE_V`는 `usize`인데 반해 `PTE_R`, `PTE_W`, `PTE_X`, `PTE_U`는 `i32`입니다. `PTE_R`, `PTE_W`, `PTE_X`, `PTE_U`가 `i32`인 이유가 있나요? 특별한 이유가 있는 것이 아니라면 모두 `usize`로 통일하는 것이 좋아 보입니다.

**Comment by jeehoonkang** [comment]
@Medowhill 혹시 bitflags를 쓰도록 변경할 수도 있을까요? https://docs.rs/bitflags/1.2.1/bitflags/
