### ISSUE TITLE
balloc: out of blocks if compiled with -O3

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/rv6#345]
`Makefile` 에서 `CFLAGS` 를 `-O` 가 아닌 `-O3` 로 수정하고 usertest를 실행하면 `writebig` 에서 `balloc: out of blocks` 오류가 발생합니다. 디버깅을 조금 해 보았는데 `-O` 이면 268개의 balloc 이 연속적으로 잘 이루어지는 반면 `-O3` 이면 112개만 성공하고 멈춥니다. 어디선가 동기화가 잘못된 것 같습니다.

**Comment by efenniht** [comment]
해당 버그는 xv6에도 존재함을 확인했습니다.

**Comment by jeehoonkang** [comment]
ㅋ... 혹시 xv6에 리포트해주시겠어요? 가능하면 fix도 하면 좋구요

**Comment by efenniht** [comment]
https://github.com/mit-pdos/xv6-riscv/issues/59 리포트했습니다.

**Comment by efenniht** [comment]
디버깅을 한 결과, `-O3` 로 컴파일하면 user binary 의 크기가 커져서, filesystem의 남은 용량이 writebig 이 write 하는 용량보다 작아 실패한다는 것을 알아냈습니다. `kernel/param.h` 와 `kernel-rs/param.rs` 의 `FSSIZE` 를 더 큰 값으로 수정하여, 잘 작동함을 확인했습니다.

**Comment by jeehoonkang** [comment]
음 문제가 아직 남아 있으니 닫으면 안될 것 같고 tracking하는게 좋을 것 같습니다. 다시 열겠습니다.
