### ISSUE TITLE
myproc() refactoring

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#354]
- #258 과 관련있는 이슈입니다.
- ---
**`myproc()`의 결과가 null이 아님을 확인하고, `get()`을 사용해 `proc.data`의 reference를 리턴하는 함수를 만드는 것을 제안합니다.**
더불어 `myproc()`을 사용하는 다른 경우들도 `ProcGuard`를 리턴하는 함수, `kill`을 체크하는 함수 등을 만들어서 `myproc()`을 감싸는 것이 어떨까요? (+ 교수님께서 관련 함수들을 Kernel의 함수로 만드는 것이 좋겠다는 코멘트를 주셨습니다.)

(예시)
```rust
// proc.rs : struct Proc
/// Return reference of ProcData.
/// This is safe because ProcData is private to the process.
pub fn deref_procdata<'a>(&self) -> &'a ProcData {
    unsafe { &*self.data.get() }
}

// proc.rs
/// Return the current struct Proc's data with immutable refercnce.
pub fn my_proc_data<'a>() -> &'a ProcData {
    // TODO: Check safety of myproc()
    let p = unsafe{myproc()};
    assert!(!p.is_null(), "my_proc_data: no myproc");
    unsafe{ (*p).deref_procdata() }
}
```
이렇게 바꾸면, proc.rs, sysfile.rs, sysproc.rs, path.rs, exec.rs, file.rs, pipe.rs, syscall.rs, trap.rs, vm.rs에서 코드 수정이 필요합니다.
아래와 같이 `myproc()`과 `UnsafeCell::get()`에 의해 발생하는 unsafe한 부분을 없앨 수 있습니다. (현재 약 37번의 `myproc()`이 호출되는데 그중에서 24번 정도가 `proc.data.get()`을 위한 호출입니다.)
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/sysproc.rs#L38
```rust
        let addr = my_proc_data().sz as i32;
```

---
아래는 추가 정보 입니다.

`myproc()` 이 사용되는 이유는 크게 3가지 입니다.
1. `proc.killed` 체크
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/console.rs#L64-L65
2. `proc.data`에 접근
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/syscall.rs#L13-L14
3. `ProcGuard`를 필요로 하는 `procinfo` 등에 접근
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/proc.rs#L978-L983

그 외에 pid, parent에 접근하는 경우가 한 두 번 존재합니다.

**Comment by jeehoonkang** [comment]
이 이슈를 혹시 두괄식으로 정리해주실 수 있으신가요?
(1) 제안을 하이레벨에서 먼저 적어주시고, (2) 구체적으로 어떤 변화가 있을지 알려주시고, (3) 왜 변화가 좋은지 적어주세요.

**Comment by jeehoonkang** [comment]
- @anemoneflower 이렇게 수정하려는 motivation이 설명되어야 합니다.
- @Medowhill @travis1829 @coolofficials 혹시 리뷰 가능하신가요?

**Comment by travis1829** [comment]
* 지금 `myproc()`이 불필요하게 unsafe을 늘리는 부분들이 꽤 있기 때문에 어차피 언젠가는 바꿔야할 부분이라고 생각합니다.
* 또, 이렇게 하면 #258 에서 말한대로 `Proc::data` field가 더 이상 pub field일 필요 또한 없어질 것 같습니다.
	* 다만, 저번 sync up에서 이야기한 대로 기존의 코드는 lock을 획득하지 않고서 `ProcData`를 접근하는 경우들이 있는데 (예: syscall.rs::fetchaddr()는 mutable reference가 필요합니다), 변경후에는 #315 에서처럼 `myproc()`을 이용해서 lock을 획득한 후 `ProcGuard`을 리턴하게 되는건지 궁금합니다.

**Comment by coolofficials** [comment]
- 제 생각에는 "myproc()의 (1)역할이 무엇이고, 현재 상태에 (2)어떤 단점(혹은 해결하고자 하는 문제)이 있고, 이를 해결하기 위해 (3)어떠한 변경을 제안한다." 순서로 하이레벨 제안이 필요할 것 같습니다.

: (1) CPU(mycpu)에서 현재 실행 중인 Process가 myproc()입니다. myproc()의 쓰임새는 다음과 같습니다.
: (2) 현재 상태에는 (서윤 님께서 언급하신 UnsafeCell을 호출하는 부분)이 있어서 reduce 가능한 unsafe block이 존재합니다.
: (3) 이를 해결(reduce)하기 위해 다음과 같은 수정을 제안합니다.

순서로 서술이 된다면 좋을 것 같습니다.

----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Medowhill** [comment]
* `myproc` 자체가 `unsafe`가 아니게 바꿀 수 있는지 고민해 보면 좋을 것 같습니다.
* `myproc` 자신도 전역 함수이고 `myproc` 안에서 `kernel` 등 다른 전역 함수를 또 호출하기 때문에 `myproc`을 되도록이면 사용하지 않는 것이 바람직하다고 생각합니다. 따라서 `myproc`의 사용을 줄일 수 있는지 먼저 고민해 보는 것도 좋을 것 같습니다.

**Comment by coolofficials** [comment]
내용적으로 이야기 하자면 저도 홍재민 님 의견에 동의합니다.
제 기억으로는 #204 의 2번 항목과 연관이 있는데, CPU가 현재 실행하고 있는 Process를 새로운 type으로 지정하는 방식으로 myproc()의 사용을 없애는 것이 좋다는 논의가 있었습니다. @efenniht 

해당 이슈를 단순 기록용으로 남겨서 설명이 부족했던 것 같습니다. 죄송합니다 :(

**Comment by anemoneflower** [comment]
리뷰 확인했습니다. 의견 주신 것을 바탕으로 고민해본 후 디자인을 좀 더 정리해서 올리겠습니다!

**Comment by anemoneflower** [comment]
#385 에서 다음 내용을 진행합니다.
- `usertrap()` 에서 아래와 같은 구조를 sys_*함수들에 전달
``` rust
struct ExecutingProc {
  ptr: *mut Proc
}
```
- sys_* 함수들에서 `myproc()`을 사용하는 대신 전달받은 `ExecutingProc`을 통해 `Proc`에 접근하게 됩니다. 
- 현재 `myproc()`을 사용할 때는 `Proc`의 존재 유무를 확인하지 않고, 많은 함수들에서 전역함수인 `myproc()`을 사용합니다. `ExecutingProc`를 리턴하기 전에 `Proc`의 존재 유무를 확인하고 sys_*함수들에 전달하면 다음과 같은 장점이 있습니다.
  - runtime cost 감소
  - 전역함수의 사용 감소
  - raw pointer에 의한 unsafe 코드 감소 (`data.get()`과 같은 코드를 `ExecutingProc`의 함수를 통해 사용하기 때문)
