### ISSUE TITLE
Initializing struct FileSystem

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#358]
1. `FileSystem`의 `superblock`, `log` 를 initialize할 때 `Once`를 사용하는 것보다 좋은 방법이 있는지 고민
2. `Superblock`과 `Sleepablelock<Log>`를 리턴하는 함수인 `FileSystem::superblock()`, `FileSystem::log()`의 safety를 명확히
3. `FileSystem.log` document

**Comment by Medowhill** [comment]
1. `Once`를 사용하는 것이 나아 보입니다.
2. 패닉은 safety를 깨는 것이 아니므로 두 메서드는 안전합니다.
3. 무엇을 어떻게 문서화하자는 것인지 분명하지 않고, 특별히 문서화해야 할 내용이 보이지 않습니다.
