### ISSUE TITLE
`Dirent::read_entry`에서 iterator 사용

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#360]
https://github.com/kaist-cp/rv6/blob/1afd6bfe99027e9e64b0c5d7c5d9d1ee9665be61/kernel-rs/src/fs/inode.rs#L209-L217

**Comment by coolofficials** [comment]
@jeehoonkang 오늘 미팅에서 나온 '의미가 불명확한 issue'의 예시입니다. 혹시 Context가 있으신가요?

**Comment by travis1829** [comment]
일단 PR #285 의 commit https://github.com/travis1829/rv6/commit/afc80b68037578f1efc3673010a39bd100f19a57 에서 추가된 것으로 보입니다.

**Comment by coolofficials** [comment]
history를 더 쫓아보니 https://github.com/kaist-cp/rv6/commit/153b3ead329a6d653608a4772dd4e85a33ca8cca 에서 추가된 TODO입니다.

PR #228 입니다.
