### ISSUE TITLE
pid, state should be methods of ProcGuard

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#363]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/proc.rs#L538-L539

**Comment by coolofficials** [comment]
@efenniht @anemoneflower 제 기억으로는 해당 refactoring은 #204 #258 이 어느정도 진행되고 cleanup 된 이후에 진행하는 것이 좋다고 했던 것 같습니다.

**Comment by anemoneflower** [comment]
#385 에서 `wakeup`을 `ProcGuard`로 옮겼습니다.

**Comment by anemoneflower** [comment]
`pid`의 경우 `allocpid()`에서 `nextpid`를 통해 설정되는데, `nextpid`가 이미 `AtomicI32`로 정의되어 있기 때문에 `killed`를 `ProcInfo`에 넣지 않은 것과 같은 이유로 `ProcInfo`에 포함하지 않아도 된다고 생각합니다. 
https://github.com/kaist-cp/rv6/blob/9d0b25a83561f04e0d06b85a465b1080d99f154a/kernel-rs/src/proc.rs#L635-L637
https://github.com/kaist-cp/rv6/blob/9d0b25a83561f04e0d06b85a465b1080d99f154a/kernel-rs/src/proc.rs#L658-L660
