### ISSUE TITLE
unnecessary use of atomic_fence()

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#364]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/spinlock.rs#L64-L66

https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/spinlock.rs#L80-L82

**Comment by travis1829** [comment]
@jeehoonkang
https://github.com/kaist-cp/rv6/commit/b7401ff248d08d80524c87ab68e4aa86b685def2#diff-edf09f9ad80e775a7fa543f2e5af3c022297b95808928288f03bb28ad349a06cL59-R66
여기서 `atomic_fence()`를 지우면서 TODO를 추가하신 것 같은데, 혹시 correctness등에 대해서 아직 생각해야 할게 남아서 그런건지, 아니면 그냥 xv6에서 달라졌다는걸 표시하시려고 그러신건지 궁금합니다.

**Comment by jeehoonkang** [comment]
@travis1829 잘 질문해주셔서 감사합니다.
- correct한건 제가 확신이 있습니다.
- todo를 남긴 의도는 주석을 업데이트해야 하기 때문인데... 동시성 프로그래밍 교과목을 훌륭하게 수강하신 분들이 적절히 업데이트 해주시면 감사하겠습니다.
