### ISSUE TITLE
virtio_disk.rs: Disk can be implemented using bitmap

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#368]
Disk can be implemented using bitmap
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/virtio_disk.rs#L41-L46

**Comment by Medowhill** [comment]
Rust에 bitmap을 제공하는 라이브러리가 두 개 있는 것 같습니다.

* https://docs.rs/bitmaps/2.1.0/bitmaps/
* https://docs.rs/bitmap/3.1.3/bitmap/

`NUM` 길이의 bitmap을 잘 만들 수 있는지 확인해 볼 필요가 있습니다.
