### ISSUE TITLE
Make MruArena and ArrayArena trait

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#369]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/arena.rs#L193-L202

https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/arena.rs#L374-L383

**Comment by coolofficials** [comment]
관련하여 정우님께 온 답변입니다.
> dup()에서 refcnt를 증가시키는 부분을 Arena trait이 아닌, MruArena나 ArrayArena trait을 따로 만들어 그곳에서 refcnt를 증가시키라는 맥락으로 기억합니다..

@travis1829 님과 논의 결과 #435 에서 자연스럽게 해결될 내용으로 판단되어 해당 PR에서 이 TODO들을 해결하고 comment를 삭제하면 될 것 같습니다. 오늘 회의에서 논의된 부분이라고 생각되어 자세한 context는 생략했습니다. @jeehoonkang @Medowhill 확인 부탁드립니다.
