### ISSUE TITLE
Safety in ArrayArena::new() and MruArena::new()

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#371]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/arena.rs#L97-L102
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/arena.rs#L238-L245

**Comment by Medowhill** [comment]
`new`가 배열을 인자로 받을 때 그 배열이 이상한 데이터를 가지고 있을 수 있다는 문제를 의미.
