### ISSUE TITLE
idiomatic initialization in FileTable::alloc_file

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#372]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/file.rs#L205-L221

**Comment by coolofficials** [comment]
#207 에서 추가된 comment입니다. 
@jeehoonkang https://github.com/kaist-cp/rv6/commit/d28972066b059796b1ebb80afccd3407cdcb4c01 에서 코드 내용을 수정하셨는데, 해당 commit이 TODO를 resolve 하지 않았다면 추가적으로 어떻게 더 idiomatic 하게 수정할 필요가 있는지 의견이 필요합니다.
