### ISSUE TITLE
Using a trait such as `pub trait SpinlockID {}`

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/rv6#375]
https://github.com/kaist-cp/rv6/blob/5bbd4f03298d5c6d011b55f59ed0b8035acdb392/kernel-rs/src/spinlock.rs#L246-L262

**Comment by travis1829** [comment]
부연설명을 추가하자면,
* 기존
```Rust
pub struct SpinlockProtected<T> {
    lock: &'static RawSpinlock,
    data: UnsafeCell<T>,
}
```
* 변경 후
```Rust
pub struct SpinlockProtected<T, U: SpinlockID> {
    lock: &'static RawSpinlock,
    data: UnsafeCell<T>,
    _marker: PhantomData<U>,
}
```
이렇게 바꾼 후, 서로 다른 `RawSpinlock`을 refer하는 `SpinlockProtected`들은 아예 서로 다른 type을 가지도록 하자는 뜻입니다.
이러면, 굳이 runtime 비용을 추가할 필요가 없습니다.

다만, 이렇더라도 프로그래머가 실수로 같은 type끼리 다른 `RawSpinlock`을 가리키게 할 수 있으므로, `SpinlockProtected::new()`를 unsafe로 해놓은 후 프로그래머가 알아서 조심하도록 해야할 수도 있습니다.

**Comment by coolofficials** [comment]
@travis1829 혹시 lock module을 만들면서 해결된 issue인가요? #430

**Comment by travis1829** [comment]
아닙니다. 아직 해결되지 않았습니다.

superseded by #475
