### ISSUE TITLE
Docs관련된 lint allow 제안

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#382]
* 현재 rv6에는 rustdocs과 관련된 기능이 lint로 금지되어 있습니다.
https://github.com/kaist-cp/rv6/blob/026a808c2922499e23941b78ae39b4d21f4ab050/kernel-rs/src/lib.rs#L16-L17
https://github.com/kaist-cp/rv6/blob/026a808c2922499e23941b78ae39b4d21f4ab050/kernel-rs/src/lib.rs#L34

  * `missing_docs`는 documentation이 없는 function을 무시/경고/금지하는 기능입니다.
(https://doc.rust-lang.org/rustdoc/lints.html#missing_docs)
  * `missing_doc_code_example`는 code example이 없는 documentation을 무시/경고/금지하는 기능입니다. 
(https://doc.rust-lang.org/rustdoc/lints.html#missing_doc_code_examples)
  * `rust_doc`은 `cargo docs` 관련된 모든 경고를 무시/경고/금지하는 기능 같습니다.

* 제 생각에는`#![deny(missing_docs)]`와 `#![deny(missing_doc_code_examples)]`를 없앤 후 `#![allow(rustdoc)]`는 켜놓는게 좋을 것 같습니다. 이러면 `cargo docs --document-private-items`를 사용해서 저희가 지금까지 만든 모든 struct들에 대한 documentation을 만들어서 읽어볼 수 있습니다. 소스코드를 직접 봐도 되지만, documentation도 꽤 깔끔한 것 같습니다.
* 또는, `#![allow(rustdoc)]` 대신 `#![allow(non_autolinks)]`를 추가한 후 inode.rs에 있는 사소한 부분만 고쳐도 `cargo docs`가 성공합니다. (`non_autolinks`를 추가해야 하는 이유는 모든 URL을 "https://..."형식이 아니라 \<https://...>형태로 표현해야 하는데, 현재 rv6에서는 대부분의 URL을 "https://..."형태로 쓰고 있기 때문입니다.)

**Comment by jeehoonkang** [comment]
cargo docs --document-private-items -A missing_docs 이런 식으로 하면 아마 missing docs여도 잘 출력될거 같은데 한번 해보시겠어요?

**Comment by travis1829** [comment]
> cargo docs --document-private-items -A missing_docs 이런 식으로 하면 아마 missing docs여도 잘 출력될거 같은데 한번 해보시겠어요?

* `-A`라는 argument는 인식하지 못하는 것 같습니다.
일단 `cargo doc --help`는 다음과 같습니다.
```
OPTIONS:
    -q, --quiet                      No output printed to stdout
        --open                       Opens the docs in a browser after the operation
    -p, --package <SPEC>...          Package to document
        --all                        Alias for --workspace (deprecated)
        --workspace                  Document all packages in the workspace
        --exclude <SPEC>...          Exclude packages from the build
        --no-deps                    Don't build documentation for dependencies
        --document-private-items     Document private items
    -j, --jobs <N>                   Number of parallel jobs, defaults to # of CPUs
        --lib                        Document only this package's library
        --bin <NAME>...              Document only the specified binary
        --bins                       Document all binaries
        --release                    Build artifacts in release mode, with optimizations
        --profile <PROFILE-NAME>     Build artifacts with the specified profile
        --features <FEATURES>...     Space or comma separated list of features to activate
        --all-features               Activate all available features
        --no-default-features        Do not activate the `default` feature
        --target <TRIPLE>...         Build for the target triple
        --target-dir <DIRECTORY>     Directory for all generated artifacts
        --manifest-path <PATH>       Path to Cargo.toml
        --message-format <FMT>...    Error format
    -v, --verbose                    Use verbose output (-vv very verbose/build.rs output)
        --color <WHEN>               Coloring: auto, always, never
        --frozen                     Require Cargo.lock and cache are up to date
        --locked                     Require Cargo.lock is up to date
        --offline                    Run without accessing the network
    -Z <FLAG>...                     Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
    -h, --help                       Prints help information
```
위 flags를 여러번 조합하더라도 에러가 안 뜨게 할 수는 없는 것 같습니다. (`cargo doc`를 시도해보면 code example이 없다거나 URL이 hyperlink가 아니라거나 하는 이유 등으로 에러가 떠서 실패합니다.)

**Comment by travis1829** [comment]
* 추가로, `missing-doc-code-examples`와 `invalid-html-tags`는 `rustdoc`의 sublint이므로, #![deny(rustdoc)]를 하실 예정이시면 앞의 두 lint는 굳이 deny를 표시할 필요가 없어 보입니다.
* `cargo doc`이 실패하는 걸 막기 위해서는
	1. #![allow(rustdoc)]를 하여 모든 경고를 무시하거나, 아니면
	2. https://github.com/kaist-cp/rv6/issues/382#issue-795834833 에서 언급한 3개의 lint를 그냥 없애고 (이러면 default로 그냥 missing-docs와 missing-doc-code-examples이 허용됩니다), rv6에서 HTML 및 URL 관련된 부분만 조금 수정하는게 좋을 것 같습니다. (다만, 이러면 앞으로 주석으로 URL을 작성할때는 항상 \<https://...> 형태로 작성해야됩니다.

제 생각에는 주석을 작성할때 굳이 이런거까지 신경쓸 필요가 없도록 하기위해 1번으로 가는게 좋을 것 같습니다.

**Comment by jeehoonkang** [comment]
@travis1829 https://github.com/rust-lang/rust-clippy 여기 있는대로 -A 옵션 넣어보세요. 저는 lint는 많이 켜면 켤수록 좋다고 생각해서 가능하면 다 넣었으면 합니다.

**Comment by travis1829** [comment]
`-A` 옵션을 사용하더라도 lib.rs에 있는 lint를 override하지는 못하는 것 같습니다.

자세히 말씀드리자면,
* default로 경고/금지되어 있는 lint들 (ex: `non_autolinks`)에 대해서는 `cargo rustdoc -- --document-private-items -A non_autolinks` 를 사용하면 더 이상 경고가 뜨지 않고 rustdoc도 성공합니다.
* 그러나, lib.rs에 명시적으로 금지해놓은 lint (ex: `missing_doc_code_examples`)에 대해서는 `cargo rustdoc -- --document-private-items -A non_autolinks -A missing_doc_code_examples`를 하더라도 여전히 code example이 없다는 에러를 띄우면서 실패합니다.

혹시 제가 실수한게 있으면 말씀해주세요. 다만, `cargo doc`이 현재 상황에서 그렇게까지 중요한 기능은 아니므로, 그냥 documentation을 만들고 싶을때만 잠깐 lib.rs에서 관련 lint을 주석처리하는 식으로 해도 되긴 할 것 같습니다.

**Comment by jeehoonkang** [comment]
- `lib.rs`에서는 해당 lint를 빼고,
- `make` 에서 cargo를 실행할때 해당 lint를 -D로 추가하면 어떨까 합니다.

어떻게 보시나요?

**Comment by travis1829** [comment]
* 그렇게 해도 괜찮을 것 같습니다.
* 다만, `cargo doc`와 관련된 lint들은 `cargo check`나 `cargo build`를 할 때는 에러를 일으키지 않고 `cargo doc`을 할때만 에러를 일으키는 것으로 보이고, 또, `make`에서는 `cargo doc`를 쓰는 일이 없으므로, 해당 lint들을 추가하더라도 큰 의미가 없을 것 같습니다.

**Comment by jeehoonkang** [comment]
아 무슨 상황인지 더 잘 이해한듯 합니다.

제 의견대로 말고 일단 @travis1829 님이 제안하는대로 PR 만들어줄래요?
(1) 개발시 가능하면 최대한 lint 켜기, (2) doc 생성에 불편함이 없도록
두가지 목표를 모두 만족하는 방향으로 만들어주시면 감사하겠습니다.

**Comment by travis1829** [comment]
알겠습니다!
