### ISSUE TITLE
PR #386 CI Failure

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#393]
PR #386 의 CI 테스트가 두 번 실패했습니다.

https://github.com/kaist-cp/rv6/runs/1811305613
https://github.com/kaist-cp/rv6/runs/1811584478

수정 없이 다시 시도했을 때는 통과했습니다.

https://github.com/kaist-cp/rv6/runs/1812677291

CI 서버가 아닌 곳(PLRG 서버, AWS EC2 인스턴스, Azure 가상 머신)에서는 아직까지 테스트를 실패한 적이 없습니다. CI 서버에서 이상한 일이 일어난 것일 수도 있지만, 아주 드물게 발생하는 버그일 수도 있으니 이슈로 기록해 둡니다.

**Comment by Medowhill** [comment]
실패한 원인은 다음과 같습니다.

```
test linkunlink: panicked at 'assertion failed: `(left != right)`
  left: `None`,
 right: `None`: Inode::lock: no type', src/fs/inode.rs:734:13
```

**Comment by anemoneflower** [comment]
#385 에서도 같은 문제가 발생했습니다.
https://github.com/kaist-cp/rv6/actions/runs/530726290

**Comment by travis1829** [comment]
혹시 몰라서 playground에서도 실험해봤는데, https://github.com/kaist-cp/rv6/commit/f06956cc66c27679d70f522b711ed34f168fce78 로 reset후 test linkunlink만 2400번 이상 시도해봤으나, 버그가 일어나지 않았습니다.

**Comment by coolofficials** [comment]
현재 문제가 관찰되지 않아 추후에 문제가 다시 발생하면 open 하겠습니다.

**Comment by travis1829** [comment]
`ArrayArena`의 `reacquire_after()`관련해서 synchronization 문제가 있는 것 같습니다.
* 일반적으로, `ArrayEntry`에 대한 접근은 `ArrayArena`의 lock에 의해서 통제되므로, `&mut ArrayEntry`와 `&ArrayEntry`가 공존하는 경우가 일어나지 않습니다.
* 다만, `ArrayArena::reacquire_after()`가 문제인 것 같습니다.
  * 이 method는 잠깐동안 `ArrayArena`의 lock을 해제합니다.
  * 이러면 1) `&mut ArrayEntry`를 사용하다가 2) reacquire_after()를 써서 Arena lock을 해제한 후 3) 다른 thread에서 `Arena::find_or_alloc()`등을 사용하여 동일한 `ArrayEntry`를 `&ArrayEntry`로 접근하게 되면,
결과적으로 `&mut ArrayEntry`와 `&ArrayEntry`가 공존하게 됩니다.
  * 실제로 위와 같은 일이 rv6내에서 `ArenaObject::finalize()`에서 일어나는 것을 확인했습니다.

**Comment by coolofficials** [comment]
@travis1829 태우님, 혹시 해당 부분 코드 snippet 혹은 링크를 남겨주실 수 있나요?

**Comment by travis1829** [comment]
`ArrayArena::reacquire_after()`는 `ArrayArena`가 user에게 제공해주는 API입니다.
https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/arena.rs#L263-L268

이에 반해, `ArenaObject::finalize()`는 user가 직접 impl해야하는 함수입니다.
https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/arena.rs#L70-L72
그리고, `ArrayArena`는 arena handle이 drop될 때 자동으로 이 `finalize()`함수를 call합니다.

그러므로, 다음과 같이 user가 `finalize()`함수 안에서 `reacquire_after()`를 사용해버리면, `&mut ArrayEntry`을 사용하던 도중에 arena의 lock을 해제시켜버릴 수 있습니다. 이러면, 다른 thread에서 동일한 `ArrayEntry`를 `&ArrayEntry`형태로 접근할 수 있습니다.

https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/fs/inode.rs#L658-L700

적어도, `ArrayArena`/`MruArena` 관점에서는 문제가 생길 수 있는 것 같습니다. 이러면 user가 올바른 방법으로만 API를 사용하더라도 data race가 생길 수 있습니다.

**Comment by travis1829** [comment]
`ArrayArena`의 synchronization은 `find_or_alloc_handle()`함수를 살짝 바꾸면 해결되는 것 같습니다. 다만, 이러면 xv6와 조금 달라지는 것 같습니다.
* 기존의 xv6/rv6: `find_or_alloc_handle()`함수가 해당하는 entry를 찾았다면, 그 entry가 현재 finalize되고 있는 상태(즉, mutable deref되고 있는 상태)이더라도 그 entry의 refcnt를 1 늘린 후 그 entry를 가리키는 handle을 리턴했습니다.
* 변경 후(PR #434): `find_or_alloc_handle()`함수가 해당하는 entry를 찾았지만, 그 entry가 현재 finalize되고 있는 상태라면, 그 entry는 그냥 skip하고 다음 entry로 넘어갑니다.

**Comment by jeehoonkang** [comment]
음.. 기존 xv6가 버그인건 아닌가요? finalize가 되고 있으면 아직 건드리면 안되는거 아닌가 해서요.

**Comment by travis1829** [comment]
제 생각에, CI failure가 일어났던 이유는 7b493ce 에서 추가한 break 때문인 것 같습니다. https://github.com/kaist-cp/rv6/pull/435#issuecomment-794799315 
* 참고: opt-level=3으로 세팅한 후 다시 노가다를 해봤더니, sandbox에서도 test linkunlink이 아주 가끔(약 30번중 1번 꼴?) 실패하는 것을 확인했습니다.
* 문제 원인: break를 추가함으로써 동일한 `Dinode`를 가리키는 `Inode`가 복수개 존재하게 됩니다. 원래는 `Inode` 내부에도 `Sleeplock`이 있으므로, `Inode`이 하나만 있을 때는 이 lock덕분에 synchronization이 유지되지만, 여러개가 중복하게 생기게 되면서 synchronization 관련 오류가 일어난 것 같습니다.

**Comment by travis1829** [comment]
@jeehoonkang 
> 음.. 기존 xv6가 버그인건 아닌가요? finalize가 되고 있으면 아직 건드리면 안되는거 아닌가 해서요.

xv6 버그는 아닌 것 같습니다. `reacquire_after()`가 사용되는 곳이 `Inode`와 `File`인데,
* `Inode`는 `nlink`가 0이된 경우에만 finalize를 하므로, 정상적인 방법으로는 `Inode`에 접근할 방법이 없고,
* `File`의 경우, `FileTable`이 `Arena::find_or_alloc_handle()`을 아예 사용하지 않으므로 (즉, `Arena::alloc_handle()`만을 사용하므로) 문제가 일어나지 않는 것 같습니다.
자세한건 a0a1ca2 을 참고해주시면 감사드리겠습니다.
