### ISSUE TITLE
Use `RemoteLock` in `Arena`

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#400]
> 다만, 추가적으로 지금처럼 **원칙적으로는** `ArrayEntry`/`MruEntry`를 access할때 항상 `Spinlock<ArrayArena<...>>`/`Spinlock<MruArena<...>>`라는 외부의 `Spinlock`을 `lock()`한 후 해야하지만, **예외적으로** `ArrayEntry`/`MruEntry`의 `data`만을 immutable하게 deref하고 싶을때만 `lock()`을 할 필요가 없는 거라면, `ArrayPtr`/`MruPtr`의 `ptr` field의 type을 `NonNull<ArrayEntry<T>>`같은 형태가 아니라 `SpinlockProtected<NonNull<ArrayEntry<T>>>`같은 형태로 `SpinlockProtected`로 감싼 형태로 바꿔야할 것 같습니다. 이러면 내부 `NonNull`을 접근하려면 외부의 `Spinlock<ArrayArena<...>>`을 `lock()`한 후에만 할 수 있도록 강제할 수 있습니다.
>   * 다만, 이걸 지금 적용하기는 힘들것 같고, 새로운 issue로 만들어서 처리하는게 좋을 것 같습니다.

_Originally posted by @travis1829 in https://github.com/kaist-cp/rv6/issues/395#issuecomment-772532659_

-----
* 위 사항을 적용시키면 좋을 것 같습니다. 이러면 프로그래밍 실수로 인해 race가 발생하는 걸 막을 수 있습니다.
* 다만, 아직은 lifetime 문제때문에 적용하기 힘듭니다. (현재 `SpinlockProtected`는 `'static` lifetime의 reference만을 받습니다.) 아마 다음의 세개의 안 중에서 하나를 선택해야할 것 같습니다.
1. `ArrayArena`/`MruArena`에 대한 reference들의 lifetime을 `'static`으로 표시
  * 실제로 이 둘은 한번 만든 후 drop되지 않으므로 지금은 이렇게 하더라도 문제가 없으나, 추후에 kernel virtualization을 하게되면 문제가 생길수도 있습니다.
2. `SpinlockProtected`이 `'static`이 아닌 lifetime도 받을 수 있도록 API를 수정
  * 그러나 이렇게 되면 lifetime을 표시해줘야하는 곳이 꽤 생깁니다. (ex: `Proc`, `ProcessSystem`... 등)
3. `SpinlockProtected`이 reference가 아니라 raw pointer를 받도록 하기
  * 이러면 불필요한 unsafe가 생길 수 있습니다.

**Comment by coolofficials** [comment]
1. 저도 `'static` reference로 표시하는 것은 향후 계획을 생각해도 올바르지 않다고 생각합니다. 3번보다는 2번의 방법이 좋을 것 같습니다. lifetime 표기가 많이 생기더라도 의미를 더 정확하고 Rust idiomatic 하게 표현하는 방법인 것 같아서요.

**Comment by travis1829** [comment]
추가적으로, Inode 등에서도 `SpinlockProtected`를 사용하면 좋을 것 같습니다.

**Comment by travis1829** [comment]
참고: https://github.com/kaist-cp/rv6/pull/430#discussion_r588496628 (`SpinlockProtected`를 좀 더 정리하기 (이름, 사용방법, API 등))

**Comment by jeehoonkang** [comment]
@travis1829 close 가능한가요?

**Comment by travis1829** [comment]
@jeehoonkang 아직인 것 같습니다.

**Comment by travis1829** [comment]
참고: 구현은 간단할것 같긴 한데, 문제는 저희가 `Rc`에 붙어있던 lifetime을 없앴으므로, `RemoteLock`에게는 `'static`을 붙여주거나 다음과 같은 방법을 써야할 것 같습니다.

```Rust
fn get_inner<'s>(&self) -> &RemoteLock<'s, ...>;
```
