### ISSUE TITLE
`PinCell<T>`을 이용하여 `Pin<&mut T>`와 `*mut T` 사이의 관계 정리하기

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#402]
요약:
1. `Spinlock`의 API 문제는 `PinCell` 같은 걸 추가해서 해결할 수 있는 문제가 아닌 것으로 보입니다.
2. 그러나, **그럼에도 `PinCell<T>`은 유용하며, rv6내에서 사용할 곳이 많이 있는 것으로 보입니다.**
-----
1.
* 먼저, `T: !Unpin`을 `PinCell`같은 wrapper로 감싸더라도, 결국 `Spinlock<PinCell<T>>`을 `lock()`하면 guard가 `DerefMut`이 가능하므로 사실상 `&mut PinCell<T>`를 얻은 효과가 생깁니다. 이걸로 `PinCell<T>`을 통째로 move하면 결국 `T`도 move됩니다.
* 그러므로, `Spinlock`부분은 `MruEntry::ListEntry`, `MruArena::ListEntry` 등에서 사용한 것과 똑같은 방법으로 `Spinlock::data` field를 pin_project의 #[pin]으로 보호해서 해결해야하는 문제로 보입니다. 즉, **`Spinlock`은 특수한 경우가 아니고 `MruEntry`, `MruArena`에서 했던것과 같은 방법을 써서 해결해야 하는 문제입니다.**
* 참고로, 이 문제는 Rust의 이름만 비슷한 다른 type들 (ex: `std::boxed::PinBox`, `pin-cell::PinCell`)등도 동일하게 적용되는 문제입니다.
-----
2.
그러나 `PinCell`은 `Pin<&mut T>`와 `*mut T` 사이의 관계를 정리하는데 도움이 될 것 같습니다.
* `Pin`은 특이하게도 새로 만들기 위해서는 unsafe fn인 `Pin::new_unchecked()`를 사용해야하는데, 이러한 이유 중 하나는 `Pin`만의 [drop guarantee](https://doc.rust-lang.org/std/pin/index.html#drop-guarantee) 때문입니다. 요약하자면, **`T`에게는 `T`가 drop될때 기존에 `T`를 가르키던 `*mut T`들을 읽더라도 UB가 생기지 않도록 이런 `*mut T`들을 모두 update해줘야하는 책임이 있습니다.** ([example](https://doc.rust-lang.org/std/pin/index.html#example-intrusive-doubly-linked-list))
  * 이를 고려하면, 사실 `*mut T`들을 immutable access하는게 꼭 unsafe여야할 필요가 없을 수 있습니다. 그렇지만, lifetime문제 때문에 그렇다고 `&T`를 사용할 수도 없습니다.
  * `*mut T`로 `T`를 mutable access하는 경우도 있지만, 이런 method들이 매우 제한적입니다. 마치, `Pin<&mut T>`가 있더라도 이걸로 실제로 `T`내부를 바꿀 수 있는 method들은 매우 제한적으로 두는 것과 비슷합니다.
* 위와 같은 것을 표현하기 위해 `PinCell`을 추가하고, `*mut T` 대신 `WeakPin<T>`라는걸 만들어서 사용하는 것도 괜찮을 것 같습니다.
  * Drop guarantee를 고려하면, `WeakPin<T>`를 immutable하게 access하는 것은 safe이여도 괜찮습니다.
  * `WeakPin<T>`로도 `T`의 내부를 변경할 수 있지만, 가능한 method들은 `Pin<&mut T>`보다도 더욱 제한적입니다.
* 다만, 아직 정리가 잘 되지 않은 것 같아, 추후 정리가 된 후 google docs를 업로드하겠습니다.

**Comment by jeehoonkang** [comment]
pin-utils, pin-project 등 pin 관련해서 crate이 여럿 있는 것 같은데, (1) 이들이 뭘 제공하는지, (2) 우리가 원하는게 있는지 알아보는게 좋을 것 같습니다.

**Comment by travis1829** [comment]
알겠습니다! 관련된 내용을 google docs에 추가하겠습니다.
다만, 위 crate들에 대해서 짧게 설명을 드리자면, `Pin::new_unchecked()`는 unsafe함수라서 `Pin`을 새로 만들려면 항상 unsafe을 거쳐가야 하는데, **굳이 unsafe이여야 하는 이유가 없을 때 이 unsafe를 macro로 생략할 수 있게 해주는 기능들입니다.**

* pin-utils
  1. **제공하는 기능**
    * [stack pinning](https://rust-lang.github.io/async-book/04_pinning/01_chapter.html#pinning-to-the-stack)과정에서의 unsafe를 생략해주고, 변수 이름의 shadowing도 자동으로 해줍니다.
  2. **저희가 필요한 부분**
  * 아직 rv6에서는 stack pinning이 필요한 곳은 딱히 없으므로, 저희가 필요하지는 않은 것 같습니다.
* pin-project
  1. **제공하는 기능**
  * [pin projection](https://doc.rust-lang.org/std/pin/index.html#projections-and-structural-pinning) _(ex: struct `A`가 struct `B`를 포함하고 있으면, `Pin<&mut A>`로부터 `Pin<&mut B>`를 얻는 과정)_ 을 할때 만들어지는 불필요한 unsafe를 생략해줍니다.
  * 추가로 자잘한 macro들(알아서 `!Unpin`이라고 표시해주기, [Pinned Drop](https://doc.rust-lang.org/std/pin/index.html#drop-implementation) _(!Unpin인 struct이 drop될 때, 인자 `&mut T`를 `Pin<&mut T>`로 바꿔야하는 과정)_ 을 할때 불필요한 unsafe 생략하기)을 지원해줍니다.
  2. **저희가 필요한 부분**
  * 저희의 경우, pin projection을 할 일이 매우 많으므로, `!Unpin`인 struct를 하나라도 포함하고 있는 struct들에 대해서는 `#[pin_project]`을 이용해서 불필요한 unsafe를 생략하면 좋을 것 같습니다. 또, `Pinned Drop`도 유용할 것으로 보입니다.

**Comment by travis1829** [comment]
https://docs.google.com/document/d/1oWMkytc2kuoojWnSRX2KCT-mIj0TOAM8oL7VNDWt4t4/edit
위 문서에 정리해봤습니다.

**Comment by Medowhill** [comment]
`WeakPin` PR(#431)을 닫았고, `Arena`는 `RcCell`을 사용해 리팩토링했으므로, 이 이슈는 닫겠습니다.
