### ISSUE TITLE
Merge kernel and pinned_kernel

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#404]
pinned_kernel을 나눠놓는건 kernel을 single object로 여기겠다는 high-level design과 어긋납니다. 하나로 합치고 kernel 전체를 pin하면 될 것 같습니다.

pin 관련 다른 할일보다 이걸 먼저 해주세요.

**Comment by travis1829** [comment]
네, #402 를 고려하면, pinned_kernel과 kernel을 합쳐도 될 것으로 보입니다.
