### ISSUE TITLE
`etrace.rs` 를 다른 프로젝트와 공유하기

### ISSUE THREAD

**Issue by leeopop** [kaist-cp/rv6#406]
## Description

etrace 내용이 다른 프로젝트에도 많이 쓰입니다.

매번 복&붙 으로 운영하면 새로운 유용한 매크로 등장 시 서로 공유하기가 어렵습니다.

하여 별도의 repo 에서 오픈소스로 공개를 하나 하면 어떨까 싶습니다.

## Reference

* 관련 매크로만 모인 crate: [etrace](https://docs.rs/etrace/1.1.1/etrace/)

**Comment by coolofficials** [comment]
@jeehoonkang 교수님, etrace repository가 archive 되어서 read-only 상태입니다 (https://github.com/KizzyCode/etrace). 혹시 Contact-info를 알아보고 메일을 보낼 필요가 있을까요??
