### ISSUE TITLE
`kernel_main()`에서 `Pin<&mut Kernel>`이 두개가 필요한 문제

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#408]
> 다만, 제가 detail을 말씀드리지 않은 것 같은데, `kernel_main()`에서 `Pin<&mut Kernel>`이 두개가 필요한 이유는 `'static` borrow때문에 그런 것 같습니다.
> 아래의 코드에서 `kernel.procs`를 `Pin<&'static mut ProcessSystem>`으로 borrow하게 되는데, (∵ `&'static ProcessSystem`으로부터 `&'static RawSpinlock`을 얻어야합니다.)
> https://github.com/kaist-cp/rv6/blob/4b1baac0567d99ad08c7fb23743b7a33810e3698/kernel-rs/src/kernel.rs#L226
> 그러나, 조금 이후에 아래의 코드에서 `kernel.procs`를 `Pin<&mut ProcessSystem>`으로 borrow해야합니다.
> https://github.com/kaist-cp/rv6/blob/4b1baac0567d99ad08c7fb23743b7a33810e3698/kernel-rs/src/kernel.rs#L248
> 
> 결국, `kernel_main()`이 완료된 후에는 사실상 `&'static ProcessSystem` 하나만 남게 되지만, `kernel_main()`을 실행하던 도중에는 잠깐동안 `&'static ProcessSystem`과 `Pin<&mut ProcessSystem>`이 공존하게 되는 것 같습니다.

_Originally posted by @travis1829 in https://github.com/kaist-cp/rv6/pull/405#discussion_r571764494_

-----
조금 더 자세히 설명을 드리자면,
1. `ProcessSystem::init()`에서 `Proc`들의 `parent` field를 initialize해줘야하는데, 이를 위해`ProcessSystem::wait_lock`을 `&'static RawSpinlock` 형태로 borrow해야합니다. 그래서, `ProcessSystem`도 `'static`하게 borrow하게 됩니다.
2. 그러나, 얼마후 `ProcessSystem::user_proc_init()`에서 아주 잠깐동안 `Pin<&mut ProcessSystem>`이 필요합니다.

제 생각에는, `Proc::parent` field들을 initialize하는 부분을 `ProcessSystem::user_proc_init()`에서 같이 처리하거나, 아니면 새로운 함수에서 처리하도록 한 후 `ProcessSystem::user_proc_init()` 이후에 실행되도록 하면 될 것 같습니다. 이러면 `ProcessSystem::init()`이 `'static` borrow가 필요없으므로 괜찮을 것 같습니다.

**Comment by travis1829** [comment]
@jeehoonkang 
오류가 일어나는 코드를 보여드리자면 다음과 같습니다.
diff: https://github.com/travis1829/rv6/commit/eea65236b255479cfe9b855f4f91f0dbf952c07c
(Line 205, 233, 259만 보시면 됩니다.)

Error at Line 259:
```
error[E0499]: cannot borrow `kernel.procs` as mutable more than once at a time
   --> src/kernel.rs:259:37
    |
233 |         unsafe { Pin::new_unchecked(&mut kernel.procs).init() };
    |                  -------------------------------------
    |                  |                  |
    |                  |                  first mutable borrow occurs here
    |                  argument requires that `kernel.procs` is borrowed for `'static`
...
259 |         unsafe { Pin::new_unchecked(&mut kernel.procs).user_proc_init() };
    |                                     ^^^^^^^^^^^^^^^^^ second mutable borrow occurs here

error: aborting due to previous error
```
`ProcessSystem::init()`이 'static borrow를 필요로해서 오류가 나는 것 같습니다.

**Comment by travis1829** [comment]
@jeehoonkang 
> 여기서 unchedked_mut을 안하면 어떻게 되나요? unchedked-pin만 하고 그걸 사용하면 모든게 잘 될거 같아서요

`unchecked_mut()`을 쓰지 않게 되면 `Kernel` 내부를 mutate하기 위해서 `project()`을 대신 사용해야 하는데, 이러면 다음과 같이 바꾸더라도 에러가 생깁니다.
https://github.com/travis1829/rv6/commit/8ccf13e381af44c5444e6e7fd8f844ebcfb3af75
```
error[E0382]: use of moved value: `kernel.procs`
   --> src/kernel.rs:259:17
    |
233 |         kernel.procs.init();
    |                      ------ `kernel.procs` moved due to this method call
...
259 |         unsafe {kernel.procs.user_proc_init() };
    |                 ^^^^^^^^^^^^ value used here after move
    |
note: this function takes ownership of the receiver `self`, which moves `kernel.procs`
   --> src/proc.rs:665:17
    |
665 |     pub fn init(self: Pin<&'static mut Self>) {
    |                 ^^^^
    = note: move occurs because `kernel.procs` has type `Pin<&mut ProcessSystem>`, which does not implement the `Copy` trait

error: aborting due to previous error
```
-----

만약 여기서 Line 233을
```Rust
kernel.procs.as_mut().init();
```
로 바꾸면 다음과 같은 에러가 생깁니다.
```
error[E0597]: `kernel.procs` does not live long enough
   --> src/kernel.rs:233:9
    |
233 |         kernel.procs.as_mut().init();
    |         ^^^^^^^^^^^^---------
    |         |
    |         borrowed value does not live long enough
    |         argument requires that `kernel.procs` is borrowed for `'static`
...
284 | }
    | - `kernel.procs` dropped here while still borrowed

error[E0505]: cannot move out of `kernel.procs` because it is borrowed
   --> src/kernel.rs:259:17
    |
233 |         kernel.procs.as_mut().init();
    |         ---------------------
    |         |
    |         borrow of `kernel.procs` occurs here
    |         argument requires that `kernel.procs` is borrowed for `'static`
...
259 |         unsafe {kernel.procs.user_proc_init() };
    |                 ^^^^^^^^^^^^ move out of `kernel.procs` occurs here

error: aborting due to 2 previous errors
```

**Comment by travis1829** [comment]
Line 259를 다음과 같이 바꿔도 비슷합니다.
```Rust
 unsafe {kernel.procs.as_mut().user_proc_init() };
```

제 생각에는 `&'static mut`와 `&mut`이 공존하는 상황을 피할 수 없는 것 같은데, 조금 더 고민해봐야겠습니다.

**Comment by Medowhill** [comment]
#454 에서 해결됨.
