### ISSUE TITLE
Using `parent` of `Proc` safely

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#420]
`Proc`의 `parent` 필드는 `MaybeUninit`으로 정의되어 있기 때문에 사용할 때 unsafe 블록이 필요합니다. 

https://github.com/kaist-cp/rv6/blob/c4caab8ec8906c453bc11d4ad6c95378bcdd750c/kernel-rs/src/proc.rs#L335-L342

`parent`는 `ProcessSystem::init`에서 초기화됩니다.

https://github.com/kaist-cp/rv6/blob/c4caab8ec8906c453bc11d4ad6c95378bcdd750c/kernel-rs/src/proc.rs#L690-L696

`ProcessSystem::init`이 커널 초기화 과정에서 호출되기 때문에 그 이후에 `parent`를 사용하는 것은 언제나 안전합니다. 하지만 `init`이 호출되었다는 사실을 표현할 방법이 없기 때문에, 현재로서는 `parent`를 사용하는 모든 메서드가 `init`이 이전에 호출되었을 것을 가정하는 unsafe 메서드로 정의될 수밖에 없습니다. 이는 상당히 많은 unsafe 블록을 코드에 추가하기 때문에 어떻게 하면 `parent`를 사용하는 것이 안전하다는 것을 보장할 수 있을지 고민이 필요합니다.

**Comment by travis1829** [comment]
다른 해결책으로, `SpinlockProtected`의 메서드 중에서 `pub const fn new()`를  1)`pub const unsafe fn zero()`와 2)`pub fn init()` 두개로 쪼개면 어떨까요? 당연하지만, `zero()`가 리턴하는 값은 `init()`하기 전까지는 쓰면 안되므로 unsafe함수입니다.

물론, 이러려면 결국 `SpinlockProtected::lock` field의 type을 `&'static RawSpinlock`에서 `*const RawSpinlock`으로 바꿔야하므로 결국에는 `SpinlockProtected` 내부에 unsafe가 늘어나겠지만, `parent`가 `MaybeUninit`일 필요가 없어지면 그보다 더 많은 unsafe가 줄어들 것 같습니다. 또한, 지금은 `SpinlockProtected`가 `Proc::parent`에서만 쓰이지만, #400 을 고려하면 추후 추가할 가능성이 있으므로 장기적으로는 이렇게 하는 것도 괜찮을 것 같습니다.

**Comment by travis1829** [comment]
참고로, 오늘 sync up에서 말씀드린, `ProcessSystem::zero()`와 `ProcessSystem::init()`을 `new()` 하나로 합치는 건 안 되는 것 같습니다. 결국 `SpinlockProtected::new()`를 하는 과정에서 `ProcessSystem`을 borrow해야하므로 `new()`함수가 리턴을 할 수 없어서 입니다.
