### ISSUE TITLE
Use `FromBytes`

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#426]
<https://docs.rs/zerocopy/0.3.0/zerocopy/trait.FromBytes.html>

`FromBytes` trait은 이를 구현한 타입이 임의의 바이트 배열(`[u8; _]`)로부터 UB 없이 만들어질 수 있다는 사실을 나타냅니다. Theseus에서 `FromBytes`를 사용하고 있습니다. rv6에도 `FromBytes`를 적용할 수 있는 곳들이 있습니다.

https://github.com/kaist-cp/rv6/blob/2f8959ecaf27a98755d8c9f943e36d8eb42faf63/kernel-rs/src/fs/inode.rs#L386-L389
https://github.com/kaist-cp/rv6/blob/2f8959ecaf27a98755d8c9f943e36d8eb42faf63/kernel-rs/src/vm.rs#L572-L575

**Comment by coolofficials** [comment]
@Medowhill 혹시 주신 두 예시의 T들이 `transmute'd to`가 safe여야하기 때문에 `FromBytes`가 아니라 `AsBytes`여야 하는건 아닌지 문의드립니다. 즉, dst가 될 수 있는 T들에게 `#[derive(AsBytes)]`를 부여하자는 말씀이신건지 아니면 다른 의미로 남겨주신건지 궁금합니다. `unsafe`를 떼려면 이 방향이 맞는 것 같아서요.

별도로 `FromBytes`를 써야 하는 다른 곳이 존재하는지는 따로 확인하겠습니다.

**Comment by Medowhill** [comment]
`read_kernel`과 `copy_in`은 임의의 `u8` slice를 `T`로 변환하는 메서드이므로 "type may safely be converted from an arbitrary byte sequence"를 의미하는 `FromBytes`를 사용하는 것이 맞다고 생각합니다. "`T` can be safely `transmute`d to `[u8; size_of::<T>()]`"라는 주석은 `&mut T`를 `&mut [u8; size_of::<T>()]`로 해석하고 값을 써도 문제가 없다는 뜻으로 작성한 것이었는데, 혼동의 여지가 많으니 "`[u8; size_of::<T>()]` can be safely `transmute`d to `T`"로 고치는 것이 나아 보이네요.

`AsBytes`라는 트레잇이 있는지는 몰랐는데 `copy_out` 등에 있는 unsafe 블록을 없애는 데 사용될 수 있을 것 같은데, 가능하다면 해당 수정도 같은 PR에서 하면 좋을 것 같습니다.

**Comment by coolofficials** [comment]
@Medowhill 제가 관련된 세부 code들을 면밀히 읽지 않고 comment를 해석한 것 같네요. Code들을 더 살펴보고 적절히 수정하겠습니다.

**Comment by coolofficials** [comment]
> `read_kernel`과 `copy_in`은 임의의 `u8` slice를 `T`로 변환하는 메서드이므로 "type may safely be converted from an arbitrary byte sequence"를 의미하는 `FromBytes`를 사용하는 것이 맞다고 생각합니다. "`T` can be safely `transmute`d to `[u8; size_of::<T>()]`"라는 주석은 `&mut T`를 `&mut [u8; size_of::<T>()]`로 해석하고 값을 써도 문제가 없다는 뜻으로 작성한 것이었는데, 혼동의 가능성이 높은 바람직하지 않은 주석이었던 것 같습니다.
> 
> `AsBytes`라는 트레잇이 있는지는 몰랐는데 `copy_out` 등에 있는 unsafe 블록을 없애는 데 사용될 수 있을 것 같습니다. 가능하다면 해당 수정도 같은 PR에서 하면 좋을 것 같습니다.

이제 정확히 이해한 것 같습니다. 이번 PR에서 주석까지 함께 수정하도록 하겠습니다.
