### ISSUE TITLE
'static lifetime 사용 지양

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#428]
현재, rv6에는 lifetime을 `'static`을 표시하는 경우가 많은데, 장기적으로는 이를 올바른 lifetime으로 바꿔서 표시해야 합니다.
물론, 현재 rv6에서 이런 struct들은 한번 만들어진 후에는 절대로 drop되지 않기는 하지만, 추후 kernel virtualization을 하게되면 이런 struct들을 drop해야할 수도 있습니다. 또, struct의 definition에 lifetime parameter를 추가하지 않기 위해서 굳이 `'static`일 필요가 없는 struct을 `'static`으로 표시한 경우도 많고, 이로 인해 다른 reference나 struct까지 `'static`으로 표시해야하는 경우도 있습니다.

장기적으로는, 이런 struct나 reference들에 `'static`이 아닌 올바른 lifetime을 표시해줘야 합니다.
- [x] Kernel
- [x] arena
- [x] ProcessSystem
- [x] SpinlockProtected

(리스트는 업데이트할 예정입니다.)

**Comment by Medowhill** [comment]
현재 `&'static str`을 제외하고 남아 있는 `'static`:

https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/kernel.rs#L60-L63

https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/proc.rs#L294-L301

https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/proc.rs#L764-L768

https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/arena/array_arena.rs#L42-L43

https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/arena/mru_arena.rs#L95-L96

**Comment by travis1829** [comment]
1. https://github.com/kaist-cp/rv6/blob/b946a9463ccee7f23328514d570de1c4ab926a28/kernel-rs/src/kernel.rs#L60-L63
    이 부분은 다음과 같이 바꾸면 좋을 것 같습니다.
    ```Rust
     unsafe fn kernel_builder_unchecked_pin<'s>() -> Pin<&'s mut KernelBuilder>
    ```
    이후, user가 말이 되는 `'s`를 사용하도록 manual하게 조심하도록 하게 해야할 것 같습니다.

2, 3. 이 부분은, `Procs`와 `Proc`에 lifetime parameter를 추가해서 해결해야할 것 같습니다.
4, 5. 이 부분은 그냥 `T`가 lifetime parameter를 가지고 있으면 안된다는 뜻인것 같은데, `ArenaObject`을 계속 mutate해야하는 `Arena`의 특성상, `lifetime parameter`를 가지지 않는 `T`만 받아들이게 하는게 맞을 것 같습니다.
