### ISSUE TITLE
Should methods of `MruArena` and `ListEntry` be unsafe?

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#429]
Rust에서 초기화되지 않은 값을 만들 때는 unsafe가 필요하지 않지만, 초기화되지 않은 상태일 수 있는 값을 사용할 때는 unsafe가 필요합니다.

* `MaybeUninit`: `pub const fn uninit() -> MaybeUninit<T>`은 unsafe가 아니지만, `pub unsafe fn assume_init(self) -> T` 등은 unsafe.
* Raw pointers: `pub const fn null<T>() -> *const T` 등은 unsafe가 아니지만, `pub unsafe fn read<T>(src: *const T) -> T` 등은 unsafe.

이와 달리, 현재 rv6의 `MruArena`와 `ListEntry`는 `init`을 호출해 초기화하기 전에 사용하면 위험함에도 불구하고 메서드들이 unsafe가 아닙니다. (`ListEntry`는 `new`만 unsafe로 되어 있습니다.)

https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/arena.rs#L294-L312
https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/list.rs#L26-L46

다른 Rust 타입과의 일관성이나 unsafe reasoning을 고려했을 때, `new`는 unsafe가 아니게 하되 `new`와 `init`을 제외한 나머지 메서드들이 unsafe가 되도록 하는 것이 낫지 않을까 합니다. 어떻게 생각하시나요?

**Comment by travis1829** [comment]
참고: 반대로 적용되는 경우도 있습니다.
ex) `Pin`의 경우 `Pin`을 새로 만드는 건 unsafe이지만 `Pin`을 사용하는 건 safe입니다.

**Comment by Medowhill** [comment]
`Pin`에 대해 조금 더 생각을 해 보았는데,

* `Pin`을 만들 때 unsafe인 이유는 초기화되지 않았을 가능성 때문이 아니라 `Pin`을 만든 뒤에 move가 일어나면 안 된다는 가정이 있기 때문이고
* `Pin`을 사용하는 API는 safe일지언정, 결국 그 내부에서 사용하는 `get_unchecked_mut`은 unsafe(물론 여기서도 초기화되지 않았을 가능성 때문이 아니라 `&mut`을 만들어서 move하면 안 된다는 가정이 있기 때문)

라는 점을 고려해 보았을 때 `Pin`이 적절한 비교 대상인지 의문이 듭니다.

**Comment by travis1829** [comment]
* 말씀하신 것처럼 `ListEntry`나 `*Arena`는 `Pin`보다는 `MaybeUninit`과 더 비슷하긴 한 것 같습니다.
* 다만, pin_project의 reasoning을 생각해보면, `get_unchecked_mut()`이 unsafe인 이유는 이 함수를 통해 얻은 `&mut`로 `T`를 move하지 말아야한다는 뜻이지, 이미 `T`가 move되었을 수도 있으므로 이를 조심해야 되서는 아닙니다. 후자에 대한 reasoning은 `Pin`을 새로 만들때 해야합니다.

**Comment by travis1829** [comment]
`PageTable<A>::uninit()`도 여기에 해당되는 것 같습니다.
https://github.com/kaist-cp/rv6/blob/2fd82e68924be42a81e56a278d07ef8eb5488a9b/kernel-rs/src/vm.rs#L232-L237
다만, 이 부분은 나중에 자연스럽게 해결될 수도 있습니다.

**Comment by Medowhill** [comment]
아마 `PageTable<A>::uninit()`은 dead code일 것입니다. #421 에서 지웠어야 했는데 빼먹었네요..

**Comment by travis1829** [comment]
확인해보니 dead code가 맞는 것 같습니다.

**Comment by Medowhill** [comment]
Ralf 글에서 `Pin::new_unchecked`에 대한 reasoning을 설명한 부분을 읽어 봅시다.

**Comment by Medowhill** [comment]
#437 과 동일한 이슈
