### ISSUE TITLE
structs that may be uninitialized

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#437]
`zero()`/`new()` 메서드와 `init()`메서드가 나누어져 있는 struct의 경우, 일반적으로 `init()`을 하기 전에는 다른 메서드를 call해서는 안됩니다. 다만, 그렇다고 다른 메서드들을 모두 unsafe fn으로 표시하면 불필요한 unsafe이 너무 많아지므로, https://github.com/kaist-cp/rv6/pull/424 에서 했던 것처럼 initialized되기 전과 initialized된 후를 서로 다른 type으로 나타내는 것이 좋을 것 같습니다.

이를 다음 struct들에 적용하면 좋을 것 같습니다.
- [x] Kernel
- [x] ProcessSystem
- [x] ListEntry
- [x] MruArena
- [x] Disk

**Comment by jeehoonkang** [comment]
저는 이게 지금 구현의 가장 큰 complication중 하나라고 생각해서, @Medowhill 님이 먼저 봐주셨으면 합니다.
