### ISSUE TITLE
pin_mut vs pin

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#438]
> rv6 내 딴데서는 (가령 kernel_unchecked_pin()) 이런 경우 "_mut"을 쓰지 않는 것으로 보이는데, 이름을 통일할 필요가 있어보입니다. pin_mut vs. pin 관련 이슈 하나 만들어주세요.
> 
_Originally posted by @jeehoonkang in https://github.com/kaist-cp/rv6/pull/430#discussion_r590338361_

`*lock`들은 `get_pin_mut()`함수가 `Pin<&mut T>`를 리턴하는데 반해,
`Kernel`은 `kernel_unchecked_pin()`함수가 `Pin<&mut Kernel>`을 리턴합니다.
이름을 일관적으로 통일해야합니다.

* Rust에서 일반적으로 `get()`함수는 `&T`를 리턴하고 `get_mut()`함수는 `&mut T`를 리턴하는 것처럼, `get_pin()`은 `Pin<&T>`를 리턴하고 `get_mut_pin()`은 `Pin<&mut T>`를 리턴하도록 하는게 좋을 것 같습니다.
* 다만, 한편으로는 현재 rv6에서는 `Pin<&T>`를 사용하는 곳이 없으므로, `pin`하면 항상 `Pin<&mut T>`을 의미하도록 하는 것도 나쁘지 않을 것 같습니다.

다른 분들은 어떻게 생각하시는지 문의드립니다.

**Comment by jeehoonkang** [comment]
- 이제 `Pin<&Self>`를 사용하므로 (e.g., `RcCell`) `get_pin`, `get_pin_mut`을 구분해야할듯 합니다.
- 관례에 따라 `get_mut_pin`이 아닌 `get_pin_mut`이라고 부르겠습니다: https://docs.rs/futures/0.3.14/futures/stream/struct.Take.html#method.get_pin_mut

**Comment by Medowhill** [comment]
`grep`으로 찾아본 결과 `get_pin`과 `get_mut_pin`이라는 이름이 사용되고 있지 않습니다.
