### ISSUE TITLE
Remove lifetime from `Rc`

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#444]
`Rc`에서 lifetime을 없애고 `Arena`가 drop될 때 남아 있는 `Rc`가 있는지 동적으로 검사하도록 수정해야 합니다. 이를 통해 `Rc`가 lifetime에 대해 invariant이기 때문에 발생하는 문제를 해결하고, rv6 여러 곳에 있는 `'static` lifetime 사용을 줄일 수 있습니다.

**Comment by Medowhill** [comment]
관련 논의
* https://github.com/kaist-cp/rv6/pull/441#discussion_r598713540
* https://github.com/kaist-cp/rv6/pull/441#discussion_r598716089
* https://github.com/kaist-cp/rv6/pull/441#discussion_r598724781

**Comment by travis1829** [comment]
사실, 이미 PR #435 에서 추가한 `StaticRefCell`이 lifetime을 사용하지 않으므로, `ArrayPtr`, `MruPtr`, `Rc`에 붙어있는 lifetime parameter를 모두 없앨 수 있을 것으로 보입니다. 다만, 이미 PR #435 가 너무 커진 것 같으므로, 이건 다른 PR에서 하는게 어떨지 제안드립니다.

**Comment by Medowhill** [comment]
`Rc`에서 lifetime을 없애면 할 일: `chdir`이 `&'static self` 대신 `&self`를  받게 만들기(https://github.com/kaist-cp/rv6/pull/441#discussion_r598724781).

**Comment by travis1829** [comment]
> `Arena`가 drop될 때 남아 있는 `Rc`가 있는지 동적으로 검사하도록 수정해야 합니다.

다만, 이 부분을 어떻게 하는게 좋을지에 대해서 의문이 있습니다.
일단 선택지가 다음과 같이 2가지 정도인 것 같은데,
* `Rc`가 남아있다면 panic하기
* `Rc`가 남아있다면 모두 drop할때까지 wait하기

이때, 후자의 경우는 user가 실수로 deadlock 등을 일으키기 쉬울 것 같습니다.
`StaticRefCell`을 예로 들면,
```Rust
let cell = StaticRefCell::new(10);
let r: Ref<usize> = cell.borrow();
drop(cell); // waits forever
drop(r);
```
이런 문제는 단순히 while loop을 쓰든 `WaitChannel`을 쓰든, 또는 single thread든 multi thread든 일어날 수 있는 일 같습니다.

lifetime을 사용하지 않는 `StaticRefCell`의 특성상, 제 생각에는 전자(`Ref` 등이 남아있다면 panic하기)가 더 적합한 semantics인 것 같은데, 다른 분들은 어떻게 생각하시는지 문의드립니다.
@Medowhill

**Comment by Medowhill** [comment]
저는 panic이 나은 것 같습니다.

**Comment by coolofficials** [comment]
저도 panic이 나은 것 같습니다. 이유는 태우님이 말씀해주신 것과 동일합니다.

**Comment by Medowhill** [comment]
`Rc`의 더 좋은 이름 고민 필요
