### ISSUE TITLE
Wrong implementation of `Stat`

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#462]
현재 `Stat`의 구현입니다.

https://github.com/kaist-cp/rv6/blob/64740ba45b6c45b6c3a0d08268e06d68714f0306/kernel-rs/src/stat.rs#L3-L19

https://github.com/kaist-cp/rv6/blob/64740ba45b6c45b6c3a0d08268e06d68714f0306/kernel-rs/src/fs/inode.rs#L102-L107

원래 xv6의 `stat` 구현입니다.

https://github.com/kaist-cp/rv6/blob/64740ba45b6c45b6c3a0d08268e06d68714f0306/kernel/stat.h#L5-L11

필드 `type`의 타입이 원래 `u16`이어야 하는데 `InodeType`으로 바뀌었습니다.

`Stat`은 fstat syscall이 일어났을 때 user memory에 제공해야 하는 자료 구조이므로 임의로 memory layout을 바꾸어서는 안 됩니다. 위와 같은 수정으로 인해 `nlink` 필드의 위치가 바뀌게 되는데, usertests에서 fstat을 아예 사용하지 않고, ls에서도 `nlink`의 값을 출력하지 않기 때문에 지금까지 이 버그가 발견되지 않은 것으로 보입니다.

**Comment by coolofficials** [comment]
가독성을 위한 Type wrapping이 불러올 수 있는 Bug의 좋은 예시인 것 같습니다. 비슷한 종류의 Bug가 더 없을지 한 번 훑어보도록 하겠습니다.
