### ISSUE TITLE
`debug_assert!`대신 `const_assert!` 사용하기

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#470]
`debug_assert!`를 `const_assert!`로 대체할 수 있으면, `const_assert!`를 사용하는게 좋을 것 같습니다.

> rv6에 여기처럼 `debug_assert!`를 `const_assert!`로 바꾸면 좋을 곳이 많을 것 같네요.
> 
_Originally posted by @travis1829 in https://github.com/kaist-cp/rv6/pull/468#discussion_r604631217_

**Comment by Medowhill** [comment]
확인 결과 현재 `const_assert!`로 대체할 수 있는 `debug_assert!`가 없습니다.
