### ISSUE TITLE
`LockProtected`의 runtime cost

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#475]
`LockProtected`는 현재 rv6에 다음과 같은 runtime cost를 추가하고 있습니다.
* `Proc`의 경우, `Procs::wait_lock`을 가리키는 reference를 추가로 저장하게 됩니다.
* `Proc`/`Rc`(추후 추가 예정)의 경우, `LockProtected::get_mut`를 하는 과정에서 `assert!`를 하게 됩니다.

이 부분에 대하여 discussion이 필요합니다.

**Comment by travis1829** [comment]
[You Can't Spell Trust Without Rust](https://curve.carleton.ca/system/files/etd/05076cd2-c1c2-4207-9667-a3ee1af58db4/etd_pdf/60a59a782199a35d15b63e1fcf16eb98/beingessner-youcantspelltrustwithoutrust.pdf) pp. 48-53
[GhostCell](http://plv.mpi-sws.org/rustbelt/ghostcell/paper.pdf)
* 위 논문들이 한것 처럼, type에 붙어있는 `'s` parameter (ex: `Guard<'s>`)를 lifetime이 아니라 identifier/token등으로 사용하면, **위 runtime cost를 모두 없앨 수 있습니다.**
* 다만, 위 방법을 적용하게 되면, **API가 사용하기 많이 불편해지게 됩니다.** 자세하게 말씀드리자면, closure 내부에서만 사용할 수 있게 됩니다.
  * 현재, Rust에는 invariant lifetime(즉, subtype이 불가능한 lifetime)을 만들 수 있는 방법이 closure를 이용하는 방법 뿐인 것으로 보입니다. (https://lord.io/blog/2020/lifetimes-as-tokens/, https://doc.rust-lang.org/nomicon/hrtb.html)
  * 그러므로, closure를 활용하면, 위에서 설명한것 처럼 lifetime을 identifier/token처럼 사용할 수 있습니다. 즉, 서로 다른 instance를 서로 다른 type처럼 인식하여, compile time에 서로를 구분할 수 있게 됩니다.
  * 다만, 반대로 말하자면, 현재 Rust에서는 closure를 활용하지 않고서는 이를 구현하기 힘든 것으로 보입니다. 그러므로, `GhostCell`이나 `LockProtected`는 closure 내부에서만 사용할 수 있게 됩니다.
    * ex)
```Rust
let vec1: Vec<u8> = vec![10, 11];
let vec2: Vec<u8> = vec![20, 21];
BrandedVec::new(vec1, move |mut bvec1: BrandedVec<u8>| { // bvec1: BrandedVec<'id1, u8>
  bvec1.push(12); let i1 = bvec1.push(13); // i1: BrandedIndex<'id1> is an index into bvec1
  BrandedVec::new(vec2, move |mut bvec2: BrandedVec<u8>| { // bvec2: BrandedVec<'id2, u8>
    let i2 = bvec2.push(22); // i2: BrandedIndex<'id2> is an index into bvec2
    *bvec2.get_mut(i2) -= 1; // No bounds check! Updates to 21
    println!("{:?}", bvec2.get(i2)); // No bounds check! Prints 21
    println!("{:?}", bvec1.get(i1)); // No bounds check! Prints 13
    // println!("{:?}", bvec2.get(i1)); // Rejected: i1 is not an index of bvec2
  }); // end of `bvec2`'s closure
}); // end of `bvec1`'s closure
```

**Comment by travis1829** [comment]
또 다른 방법으로는, lifetime 대신 const generic (ex: const usize)을 사용하는 방법이 있습니다.
다만, const generic을 사용하는 경우, lifetime과는 다르게, user가 직접 조심해서 **서로 다른 instance에 서로 다른 const usize를 붙여주어야 합니다.**

**Comment by travis1829** [comment]
https://github.com/kaist-cp/rv6/issues/475#issuecomment-814269420 를 구현한 예
```Rust
type Id<'id> = PhantomData<Cell<&'id mut ()>>;

pub struct BrandedSpinlock<'id, T> {
    _marker: Id<'id>,
    lock: Spinlock<T>,
}

pub struct BrandedSpinlockGuard<'id, 's, T> {
    _marker: Id<'id>,
    guard: SpinlockGuard<'s, T>,
}

impl<'id, T> BrandedSpinlock<'id, T> {
    pub fn new<F: for<'new_id> FnOnce(BrandedSpinlock<'new_id, T>) -> R, R>(name: &'static str, data: T, f: F) -> R {
        f(Self {
            _marker: PhantomData,
            lock: Spinlock::new(name, data),
        })
    }

    pub fn lock(&self) -> BrandedSpinlockGuard<'id, '_, T> {
        BrandedSpinlockGuard {
            _marker: PhantomData,
            guard: self.lock.lock(),
        }
    }

    // for test
    pub fn get_pin_mut_test<'s>(_lock: &Self, guard: &'s mut BrandedSpinlockGuard<'id, '_, T>) -> Pin<&'s mut T> {
        guard.guard.get_pin_mut()
    }
}

fn test() {
    BrandedSpinlock::new("lock1", 10, |lock1| {
        BrandedSpinlock::new("lock2", 20, |lock2| {
            let mut guard1 = lock1.lock();
            let mut guard2 = lock2.lock();

            assert!(*BrandedSpinlock::get_pin_mut_test(&lock1, &mut guard1) == 10);
            assert!(*BrandedSpinlock::get_pin_mut_test(&lock2, &mut guard2) == 20);

            //assert!(*BrandedSpinlock::get_pin_mut_test(&lock1, &mut guard2) == 20); // Error! Compile fails!
        });
    });
}
```

**Comment by travis1829** [comment]
또 다른 방법으로는, lifetime 대신 const generic (ex: const usize)을 사용하는 방법이 있습니다.
다만, const generic을 사용하는 경우, lifetime과는 다르게, user가 직접 조심해서 **서로 다른 instance에 서로 다른 const usize를 붙여주어야 합니다.**

**Comment by travis1829** [comment]
다만, 이를 위해서는 
* `Kernel` -> `Kernel<'id>`로 바꾸고,
* `kernel()`와 같은 전역함수의 signature를 다음과 같이 바꿔야할 것 같습니다.

이전:
```Rust
pub unsafe fn kernel() -> &'static Kernel;

// usage example
kernel().procs().wakeup_pool(...);
```
이후:
```Rust
pub unsafe fn kernel<F: for<'new_id> FnOnce(Kernel<'new_id>) -> R, R>(f: F) -> R;

// usage example
kernel(|kernel| {
    kernel.procs().wakeup_pool(...);
);
```

**Comment by travis1829** [comment]
추가적으로, 차라리 이걸 일반화해서 `Branded` type을 추가해보는 것도 매우 좋을 것 같습니다.
* 서로 다른 instance를 compile time에 구분해야하는 경우는 rv6 이외에도 매우 많을 것 같습니다.
* `Branded`는 `Pin`과 비슷하게, `Branded::new`만 unsafe인 wrapper입니다. 아마 다음과 같은 API를 가지게될 것 같습니다.
```Rust
pub struct Branded<'id, T> {
    id: Id<'id>,
    data: T,
}

impl<'id, T> Branded<'id, T> {
    /// Wraps `T` inside a `Branded` with a fresh, unique `'id`.
    pub unsafe fn new<F: for<'new_id> FnOnce(Branded<'new_id, T>) -> R>(data: T, f: F) -> R {
        f(Self {
            id: PhantomData,
            data: T,
        });
    }

    pub fn map<F: FnOnce(Self) -> U>(&self) -> Branded<'id, U> {
        // Omitted
    }
}
```

이러면, Rust에서 branded type들을 closure안에서만 쓸 수 있다는 문제점을 해결할 수 있을 것 같습니다.

**Comment by jeehoonkang** [comment]
> Superceded in #479

@travis1829 그럼 이 이슈는 닫아도 되나요?

**Comment by travis1829** [comment]
네, 제가 닫겠습니다.
