### ISSUE TITLE
Use `Branded<'id, &T>` to represent branded types

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/rv6#479]
## Motivation
현재 rv6에는 branded type을 적용하면
1) unsafe로 표시된 곳들(ex: `Arena`, `Procs`의 method들)을 없애거나,
2) runtime cost가 발생하는 곳(ex: `RemoteLock`)을 없앨 수 있습니다.
### 1. unsafe로 표시된 곳
  * **예1: 현재 `Arena::{dup, dealloc}`이나 `Rc::from_unchecked`와 같은 함수들은 unsafe fn으로 표시되어 있습니다.**
    * ex: https://github.com/kaist-cp/rv6/blob/215ff5c682207b3f3f2caedf6d7685419e00950a/kernel-rs/src/arena.rs#L53
    * `Arena::{find_or_alloc_handle, alloc_handle}`와 같은 method를 사용하면, `Arena`로부터 `Handle`을 얻을 수 있습니다.
    * 그러나, 이 `Handle`이 어떤 `Arena` instance로부터 온 것인지는 compile time에 확인할 수 없습니다.
    * `Arena::{dup, dealloc}`와 같은 method는 이 `Handle`이 정말 이 `Arena` instance로부터 온 경우에만 사용해야하므로, 위 method들을 unsafe로 표시할 수 밖에 없습니다. `Rc::from_unchecked`도 마찬가지입니다.
  * **예2: 현재 `Procs`의 상당수의 method들은 추후 unsafe fn으로 바꿔야할 여지가 다분합니다.** (potential unsafe fn)
    * ex: https://github.com/kaist-cp/rv6/blob/215ff5c682207b3f3f2caedf6d7685419e00950a/kernel-rs/src/proc.rs#L911
    * 위 함수는 만약 복수의 `Procs`가 존재할 수 있다면 문제를 일으킬 수 있습니다. 이 함수가 주어진 `proc`이 정말 `self: Procs`의 process 중 하나라는 것을 runtime check을 통해 확인도록 변경하거나, 또는 이 함수를 unsafe fn으로 변경해야 합니다.
    * 이외에도 `Procs::{reparent, wait, exit_current}` 등에도 동일한 문제가 존재하는 것으로 보입니다.
  * 이외에도 이런 예가 많은 것으로 보이는데, `Branded`를 사용하면 이런 곳을 없앨 수 있습니다.
### 2. runtime cost가 발생하는 곳
  * **예: 현재 `RemoteLock`은 runtime cost가 존재합니다. (#475)**
    * `Lock`을 borrow하면 `RemoteLock`을 얻을 수 있습니다.
    * `Lock`을 `lock()`해서 얻은 `Guard`를 이용하면, `RemoteLock`의 data를 읽을 수 있습니다. 그러나, 이때 `Lock`은 반드시 `RemoteLock`이 처음에 borrow했던 그 `Lock` instance여야만 합니다.
    * 이를 compile time에 표현할 수 없으므로, 현재는 dynamic check을 이용하고 있습니다.
  * `Branded`를 사용하면, 이런 runtime cost를 없앨 수 있습니다.

정리하자면, 현재 rv6에서는 위와 같은 문제를 만났을 때,
1) unsafe fn으로 표시하여 caller가 manual하게 체크하도록 하거나,
2) runtime check을 이용하거나,

둘 중 하나의 방법을 선택해서 해결하고 있다고 할 수 있습니다.

## Suggestion
위와 같은 패턴을 일괄적으로 표현하고, 또, unsafe를 줄이기 위해, `Branded<'id, &T>`라는 type을 사용하는 것을 제안합니다.
* API는 다음과 같습니다.
  * safe fn인 `Branded::new`를 사용하면 `&T`를 `Branded<'id, &T>`로 변환할 수 있습니다. 여기서, `'id`는 invariant한 lifetime입니다.
  * unsafe fn인 `Branded::map`을 사용하면 `Branded<'id, &T>`로부터 `Branded<'id, &U>`를 얻을 수 있습니다. 일반적으로는, 이 함수를 safe한 API로 감싸서 사용해야 합니다.

### 1. `Branded`을 사용하면, function argument들이 동일한 brand아래에 있어야만 한다는 것을 명시적으로 나타낼 수 있습니다.
  * ex: 위의 `Arena::dup`를 예로 들면,

  이전:
  ```Rust
  unsafe fn dup(&self, handle: &Ref<Self::Data>) -> Ref<Self::Data>;
  ```
  이후:
  ```Rust
  fn dup(self: Branded<'id, &Self>, handle: Branded<'id, &Ref<Self::Data>>) -> Branded<'id, Ref<Self::Data>>;
  ```
### 2. `Branded`을 사용하면 unsafe를 줄일 수 있을 것으로 보입니다.
  *   `Arena::{dup, dealloc}`, `Rc::from_unchecked` 이나 `Procs::{reparent, wait, fork, exit_current}`를 모두 safe fn으로 변경할 수 있습니다.
  * 또, `Branded::map`을 safe API로 감싸면, user가 직접 `Branded::map`을 사용할 필요가 없습니다. 예를 들어, `Arena::alloc_handle`의 경우, 현재는 `&Arena`를 받아서 `&Handle`을 리턴하는데, 이걸 `Branded<'id, &Arena>`를 받아서 `Branded<'id, &Handle>`을 리턴하도록 변경한다면, user가 `Branded::map`을 사용할 필요가 없어집니다.
### 3. 부수적으로, `Branded`을 사용하면 현재 Rust에서 branded type를 구현한 다른 type들 (ex: `BrandedVec`, `GhostCell`, `LCell` 등)이 가지고 있는 문제점들을 해결할 수 있습니다.
  * 이전의 type들은 `T`를 consume한 후 closure내부에서만 사용할 수 있는 branded type를 반환하므로, `T`를 다른 곳에 저장할 수 없다는 문제점이 있었습니다.
  * 위와 같이 `Branded`를 사용하면 이 문제를 해결할 수 있습니다. `Branded`는 `T`를 consume하지 않으며, `Pin`과 비슷하게 `&T`/`&mut T`를 consume합니다.

**Comment by Medowhill** [comment]
GhostCell 논문을 살짝 봤는데, 일단 제 예상대로 `Branded`는 singleton이라 보기 어려운 것 같습니다. `BrandedIndex`만 해도 한 타입의 값이 여러 개 존재하니까요. 물론 `BrandedVec`은 singleton이라고 말할 수 있겠습니다. Singleton이라는 단어를 다른 뜻으로 사용한 것이라면 알려 주세요.

그리고, 여러 `T`에 대한 `Branded<T>` 사이에서 공통된 의미를 찾을 수 있다고 생각하지는 않습니다. `BrandedVec`과 `BrandedIndex`만 해도 상당히 다른 특성을 가집니다. 게다가, 한 타입을 두 가지 이상의 방법으로 branding하고 싶을 수도 있습니다. 그래서 제 생각에는 `Branded` 타입을 일반적으로 정의하는 것보다는 GhostCell 논문에서 한 것처럼 필요한 경우마다 `BrandedXXX` 타입을 새로 정의해서 쓰는 편이 나은 것 같습니다.

**Comment by travis1829** [comment]
> GhostCell 논문을 살짝 봤는데, 일단 제 예상대로 Branded는 singleton이라 보기 어려운 것 같습니다. BrandedIndex만 해도 한 타입의 값이 여러 개 존재하니까요. 물론 BrandedVec은 singleton이라고 말할 수 있겠습니다. Singleton이라는 단어를 다른 뜻으로 사용한 것이라면 알려 주세요.

네, 맞습니다. 제가 말씀드리고 싶었던 것도, 처음 `Branded::new`로 만들어낸 `Branded`은 singleton type이라는 것이였습니다.

> 그리고, 여러 T에 대한 Branded<T> 사이에서 공통된 의미를 찾을 수 있다고 생각하지는 않습니다. BrandedVec과 BrandedIndex만 해도 상당히 다른 특성을 가집니다.

> 그래서 제 생각에는 Branded 타입을 일반적으로 정의하는 것보다는 GhostCell 논문에서 한 것처럼 필요한 경우마다 BrandedXXX 타입을 새로 정의해서 쓰는 편이 나은 것 같습니다.

말씀하시려는 바가 뭔지 알겠습니다. 다만, 제가 생각하는 `Branded`는 concrete한 type을 가지고 있는 wrapper라기 보다는, Haskell의 경우와 비슷하게 일종의 primitive에 더 가까우며, 이걸 무슨 뜻으로 해석할 지는 user에게 달려있다고 생각합니다.
* 이 문제는 `GhostCell`이 한 것과 비슷하게, `Branded`를 그대로 쓰지 말고, `pub struct BrandedProcs<'id>(Branded<'id, &Procs>);`와 같은 식으로 감싸서 사용하면 될 것 같습니다. 이렇게 하면, `Branded`를 구현하기 위해 비슷한 code를 반복하지 않아도 됩니다.
* `Branded`는 branded type이라는 primitive를 safe한 API로 표현하기만 하면 된다고 생각합니다. 또, 필요하다면, singleton type인 `Branded`와 그렇지 않는 `FromBranded` 두 가지로 나눌수도 있다고 생각합니다.

> 게다가, 한 타입을 두 가지 이상의 방법으로 branding하고 싶을 수도 있습니다. 

말씀하시려는 바를 제대로 이해했는지 모르겠지만, 이 문제는 같은 instance에 대하여 `Branded::new`를 여러번 하면 해결된다고 생각합니다. 이러면 여러개의 서로 다른 `'id`가 붙게 됩니다.

**Comment by travis1829** [comment]
물론, https://github.com/kaist-cp/rv6/issues/479#issuecomment-818762919 를 반영하려면 PR #481 를 조금 변경해야 하는 것은 맞습니다.

**Comment by Medowhill** [comment]
예를 들어, 올바른 인덱스를 제공하는 `BrandedVec`, 그리고 (억지스럽지만) 짝수인 올바른 인덱스를 제공하는 `BrandedVec`, 이처럼 두 종류를 생각할 때, `BrandedVec`과 `EvenBrandedVec`의 두 타입을 제공할 수 있겠지만, `Branded`를 사용하게 되면, `Branded<Vec>`하나밖에 없으므로 두 종류의 `BrandedVec`을 만들 수 없을 것 같다는 뜻이었습니다. 이 문제 역시 말씀하신 것처럼 `Branded`를 감싸서 사용하면 해결 가능해 보입니다.

`Branded` 자체는 아무런 의미가 없고, 그냥 `Id`와 임의의 타입의 순서쌍을 나타내는 타입으로 이해하되, 말씀하신 것처럼 `Branded`를 사용해 `BrandedXXX`를 구현하는 것이 가장 좋은 방법인 것 같습니다. 이 경우, `Branded::brand` 메서드는 없애거나 safe 메서드로 바꾸는 것이 맞지 않을까 합니다.

**Comment by travis1829** [comment]
알겠습니다.
* 정리하자면, `Branded`는 `Branded<'id, T>`와 `Branded<'id, U>`가
  * **서로 어떠한 관계가 있다**를 표현해주는 primitive이지만,
  * **그 관계가 무엇인지**는 정해놓지 않았으며, 이를 정하는 것은 user에게 달려있다고 생각합니다.
* 추가로, 위에서 말씀드린 것처럼 `Branded`를 1) `Branded`와 2) `FromBranded`로 나누게되면, `Branded`와 `FromBranded`의 의미가 좀 더 명확해질 것 같습니다.
  * `Branded<'id, T>` : singleton type
  * `FromBranded<'id, U>` : An instance derived from the singleton type `Branded<'id, T>`

**Comment by Medowhill** [comment]
`Branded<'id, T>`에서 `Branded<'id, S>`를 만들고 `Branded<'id, S>`에서 다시 `Branded<'id, U>`를 만드는 일을 할 수 있기 때문에 둘을 나누면 안 된다고 생각합니다. rv6만 해도 `Kernel` -> `Procs` -> `Proc`의 관계가 존재하는 것 같습니다.

**Comment by travis1829** [comment]
저도 그 생각을 했었는데, 만약에
* `FromBranded`에게도 `FromBranded::brand` method을 추가하고,
* `FromBranded`의 의미를 An instance derived from the singleton type `Branded<'id, T>` or another `FromBranded`
로 바꾸면 가능은 해보입니다.

다만, 사실 `Branded`와 `FromBranded`를 구분하고 싶지 않은 상황도 있을 수 있을 것 같아, 좋은 방법인지는 잘 모르겠습니다.

**Comment by travis1829** [comment]
* `Branded`는 PR #496 에서 추가되었으므로 이 issue는 close합니다.
* 나머지 부분 : Superceded by #494
