### ISSUE TITLE
Representing thread local access

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#483]
* `CurrentProc`은 현재 실행 중인 프로세스의 `Proc`을 나타냅니다. `Proc`이 가지고 있는 `ProcData`는 `UnsafeCell` 안에 들어 있는데, `CurrentProc`은 `ProcData`의 mutable reference를 제공하는 safe 메서드를 가지고 있습니다. 이것이 가능한 이유는 `ProcData`는 다른 프로세스에서 접근하지 않기 때문입니다.
https://github.com/kaist-cp/rv6/blob/215ff5c682207b3f3f2caedf6d7685419e00950a/kernel-rs/src/proc.rs#L355-L358
* `Cpu`는 CPU의 상태를 나타냅니다. `Kernel`은 `Cpu`를 `UnsafeCell` 안에 넣은 상태로 가지고 있습니다. `Cpu`에는 그 `Cpu`에 해당하는 CPU에서 실행 중인 스레드만 접근하므로 인터럽트가 꺼져 있다면 `Cpu`에 대한 유일한 접근이 보장됩니다. #476 에서는 이 사실을 공략해 `&mut HeldInterrupts`를 받아 `&mut Cpu`를 제공하는 메서드인 `current_cpu`를 추가했습니다.
https://github.com/kaist-cp/rv6/blob/b21d1453659716209d40d93cda88fe394df56fba/kernel-rs/src/kernel.rs#L181-L184

그러나 이런 설계는 안전하지 않습니다.
* `CurrentProc`을 여러 개 만들면 동일한 `ProcData`에 대한 mutable reference가 여러 개 생길 수 있습니다.
* `HeldInterrupts`를 여러 개 만들면 동일한 `Cpu`에 대한 mutable reference가 여러 개 생길 수 있습니다.

간단한 해결책은 `current_proc` 메서드와 `current_cpu` 메서드를 모두 unsafe로 바꾸는 것입니다. Safe 메서드로 유지하고 싶다면 runtime cost를 추가해 `RefCell`처럼 이미 만들어진 reference가 있는지 검사해야 할 텐데 좋은 방법은 아니라 생각합니다.

이 문제는 "타입 `A`에 `UnsafeCell<B>` 타입의 필드 `f`가 있을 때, `A` 타입의 값은 여러 스레드에서 접근하지만 `f`는 특정 스레드에서만 접근 가능하다면, 어떻게 해야 `f`에 대한 안전한 접근을 허용할 수 있는가"로 일반화 가능해 보이며, 흥미로운 sharing pattern이라고 생각합니다. 이 문제에 대한 더 좋은 해결책이 존재할까요?

**Comment by travis1829** [comment]
좀 더 자세히 읽어봐야겠지만, [`LCell`](https://docs.rs/qcell/0.4.1/qcell/struct.LCellOwner.html) (또는 `GhostCell`)을 응용하면 가능할 것 같습니다.

* `current_proc`이나 `current_cpu`가 `CurrentProc`/`Cpu`가 아니라 `LCell<CurrentProc>`/`LCell<Cpu>`를 리턴하도록 변경합니다.
  * `LCell`의 내부 data를 read하기 위해서는 `&LCellOwner`가 필요하고, mutate하기 위해서는 `&mut LCellOwner`가 필요합니다.
* `LCellOwner`는 어차피 zero-sized이므로, `usertrap()`이 시작할 때 argument의 하나로 제공합니다,
  * `usertrap()`이 끝나면, `LCellOwner`도 drop해야 합니다.
  * 또는, `Kernel`에 `LCellOwner`를 리턴하는 unsafe method를 추가할 수도 있겠습니다.

**Comment by travis1829** [comment]
오늘 교수님, 홍재민님과 논의를 해봤는데,
* `CurrentProc`을 단순히 current proc을 가리키는 reference로만 쓰지말고,
* 우리가 현재 kernel mode에 진입했음을 나타내는 type이자, 이 current proc의 data를 mutate할 수 있음을 나타내는 handle로 사용하는게 좋을 것 같습니다.
* 또한, 이 `CurrentProc`을 이용해서 갑자기 `kernel()` global function call을 하는 곳을 줄이도록 refactoring을 하면 좋을 것 같습니다.
* 추가적으로, 이름을 변경하면 좋을 것 같습니다.

**Comment by travis1829** [comment]
저번에 논의한대로 1) `CurrentProc`에 `kernel: &Kernel` field를 넣고, 그 대신, 2) `Kernel`이나 `Proc`의 method들이 `&Kernel`/`&Procs`를 받지 않고`CurrentProc::kernel`/`CurrentProc::procs` method를 통해 이걸 받도록 변경하려고 했는데, 생각보다 잘 안되는 것 같습니다.
* 위와 같이 변경하게 되면, `&Kernel`/`&Proc`이 `&mut CurrentProc`와 공존하지 못합니다. 즉, `CurrentProc::kernel`/`CurrentProc::procs` method를 써서 얻은  `&Kernel`/`&Proc`가 살아있는 동안에는 `CurrentProc`이 immutably borrowed된 상태이므로, `&mut CurrentProc`이 필요한 method들을 사용할 수 없습니다.
 
  * ex1) `Procs`의 `Proc`들을 iterate하는 동안 `&mut CurrentProc`을 사용할 수 없게 됩니다.
  https://github.com/kaist-cp/rv6/blob/a17a83c362cb59619040d0a620c04c8d14974763/kernel-rs/src/proc.rs#L972-L995
  예로, 위 코드의 경우, for loop이 진행되는 동안에는 `Procs`를 immutably borrow하게 됩니다. 그러나, L983에서 `&mut CurrentProc`을 사용하게 됩니다.

  * ex2) `FsTransaction`이 살아있는 동안 `&mut CurrentProc`을 사용할 수 없게 됩니다.
  https://github.com/kaist-cp/rv6/blob/a17a83c362cb59619040d0a620c04c8d14974763/kernel-rs/src/syscall/file.rs#L270-L279
  위 코드의 경우, `_tx`가 살아있는 동안 `Kernel`을 immutably borrow하게 되는데, L277에서 `&mut CurrentProc`을 사용하게 됩니다.
  비슷한 문제가 `Kernel::{chdir, open}`, `File::write`, `Procs::exit_current` 등에서도 발생합니다.

* 추가적으로, `Kernel`이나 `Procs`의 method들이 `&self`를 받지 않는게 자연스러운지 잘 모르겠습니다.

**Comment by Medowhill** [comment]
해당 주제는 #490 에서 의논합시다.

**Comment by travis1829** [comment]
네, 사실 #490 에서 한것처럼 `KernelCtx`를 추가하면 https://github.com/kaist-cp/rv6/issues/483#issuecomment-820937140 는 해결될 것 같습니다.

**Comment by Medowhill** [comment]
아직 `Cpu`에 대한 thread local access는 제대로 표현되지 않았습니다. `HeldInterrupts`를 추가하면서 해결해 보겠습니다.
