### ISSUE TITLE
`RcCell` violates stacked borrows

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#487]
현재의 `RcCell`과 #485 의 새로운 `RcCell`(아직 이름이 정해지지 않았으므로, 현재의 `RcCell`과 구분하기 위해 PR에서 사용한 `StackRc`라는 이름으로 부르겠습니다)은 모두 UB를 일으킵니다. 실제로 UB가 탐지되는지 모두 Miri로 확인했습니다.

* `RcCell`
```rust
let mut cell = RcCell::new(0);
let r = cell.try_borrow().unwrap();
&mut cell;
println!("{}", r.deref());
```
`r`은 `cell`에 대한 포인터를 가지고 있습니다. 셋째 줄에서 `cell`을 다시 mutably borrow하기 때문에 그 이전까지 존재하던 `cell`을 가리키는 모든 포인터가 무효화됩니다. 셋째 줄 이후에도 여전히 `r`이 살아 있기 때문에 `r`을 사용하여 UB를 일으킬 수 있습니다.
위 예시는 단순히 무효화된 포인터를 사용해 "이론상" UB인 것이지만, 실제로 컴파일러 최적화에 문제를 일으키는 예시도 만들 수 있습니다.
```rust
let mut cell = RcCell::new(0);
let r = cell.try_borrow().unwrap();
let m = &mut cell;
drop(r);
println!("{}", m.is_borrowed());
```
`m`은 mutable reference이므로 유일성이 보장되어 `m`을 사용하지 않는 코드는 `m`의 동작에 영향을 줄 수 없습니다. 따라서 컴파일러가 넷째 줄과 다섯째 줄의 순서를 임의로 바꾸어도 동작이 바뀌지 않아야 합니다. 그러나, `drop`이 먼저 오면 `false`가 출력되고, `println!`이 먼저 오면 `true`가 출력됩니다.
* `StackRc`
`RcCell`의 경우와 비슷합니다.
```rust
let mut rc_box = StackRcBox::new(0);
let pinned = unsafe { Pin::new_unchecked(&mut rc_box) };
let r = StackRc::new(pinned);
&mut rc_box;
println!("{}", r.deref());
```
`r`은 `rc_box`에 대한 포인터를 가지고 있습니다. 넷째 줄에서 `rc_box`를 다시 mutably borrow하기 때문에 그 이전까지 존재하던 `rc_box`을 가리키는 모든 포인터가 무효화됩니다. 넷째 줄 이후에도 여전히 `r`이 살아 있기 때문에 `r`을 사용하여 UB를 일으킬 수 있습니다.
동일하게, 실제로 컴파일러 최적화에 문제를 일으킬 수 있습니다.
```rust
let mut rc_box = StackRcBox::new(0);
let pinned = unsafe { Pin::new_unchecked(&mut rc_box) };
let r = StackRc::new(pinned);
let m = &mut rc_box;
drop(r);
println!("{}", m.has_reference());
```
컴파일러가 마지막 두 줄의 순서를 임의로 바꾸어도 동작이 바뀌지 않아야 합니다. 그러나, `drop`이 먼저 오면 `false`가 출력되고, `println!`이 먼저 오면 `true`가 출력됩니다.

이런 문제는 `RcCell`의 원본인 `RefCell`이나 `StackRc`의 원본인 `Rc`에는 없는 문제입니다.
* `RefCell`에서 만들어진 `Ref`는 lifetime을 통해 `RefCell` 객체와 연결되어 있기 때문에 `Ref`가 살아 있는 동안은 같은 `RefCell`을 가리키는 mutable reference를 만들 수 없습니다. 그러나 `RcCell`은 lifetime 연결을 없앴기 때문에 이런 문제가 발생합니다.
* `Rc`의 경우, `Rc`가 가리키는 데이터인 `RcBox`는 힙에 위치한 상태로, `Rc`를 통하지 않고 접근할 방법이 없습니다. 그러나, `StackRc`의 경우에는 `StackRcBox`가 힙에 위치해 있지 않기 때문에 `StackRc`를 통하지 않고도 접근할 수 있기 때문에 이런 문제가 발생합니다.

**Comment by travis1829** [comment]
혹시 `RcCell`을 [`Frozen`](https://docs.rs/frozen/1.0.0/frozen/struct.Frozen.html) 같은 걸로 감싸서만 사용하도록 강제하면 문제가 해결되는지 문의드립니다. 이러면, `&mut RcCell`을 얻을 방법이 없고, `&RcCell`형태로만 접근할 수 있습니다.

혹시, 위 방법으로 해결되지 않는다면, `RcCell`에는 최소한의 method만 남기고, 문제가 될 수 있는 method는 모두 없애는 것도 한가지 방법일 것 같습니다.

**Comment by travis1829** [comment]
https://github.com/kaist-cp/rv6/issues/487#issuecomment-818442290 에 몇가지 질문을 추가하자면,
* 혹시, `RcCell`을 `Frozen`으로 감싸더라도, &mut Frozen(또는 Pin<&mut Frozen>)을 얻게 되면 문제가 생기는지 문의드립니다.
* 또는, 지금은 `RcCell`의 layout이
  ```Rust
  pub struct RcCell<T> {
    data: UnsafeCell<T>,
    refcnt: Cell<usize>,
    _pin: PhantomPinned,
  }
  ```
  인데, 이걸 순서를 바꿔서
   ```Rust
  pub struct RcCell<T> {
    refcnt: Cell<usize>,
    data: UnsafeCell<T>,
    _pin: PhantomPinned,
  }
  ```
  로 바꾸면 문제가 해결되는지 문의드립니다.

**Comment by travis1829** [comment]
* 확실하지는 않지만, 일단은 `RcCell`을 단순히 `Frozen`로 감싸거나 layout을 변경하는 것 만으로는 문제가 해결되지는 않는 것 같습니다. (Miri에서 실험해봤습니다.)
  * 제 생각에는, 이 문제는 "`RcCell`은 `Pin<&mut RcCell>`을 가지고서 할 수 있는게 딱히 없고, 애초에, `Pin<&mut RcCell>`형태로 접근해서는 안된다"고 comment를 추가하든가 해서 해결해야하는 문제 같습니다.
* 추가로, xv6의 semantics를 동일하게 유지하면서 stacked borrow rules로 동시에 지키기는 많이 힘들 것 같습니다.
  * 지금의 `Spinlock`은 `lock()`을 하면 `Pin<&mut Arena>`를 얻을 수 있고, 이러면 이전의 `Rc`들이 모두 invalidate됩니다.
  * 다만, 그렇다고 `ReadOnlyLock`같은 걸 추가하더라도, `ReadOnlyLock` 자체를 또 `Pin<&mut ReadOnlyLock>`으로 접근하게 되면 동일한 문제가 발생할 것 같습니다.
  * 결국, 단순히 wrapper를 추가해서 해결할 수 있는 문제는 아닌 것 같고, 어쩔 수 없이 user가 알아서 조심하도록 해야하는 부분 같습니다.

**Comment by travis1829** [comment]
`Pin2` (가칭)을 추가하면 좋을 것 같습니다.
* `Pin`의 user contract : do not move the referent
* `Pin2`의 user contract : do not &mut the referent

**Comment by Medowhill** [comment]
#553
