### ISSUE TITLE
Safety of `brand()` method

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#498]
https://github.com/kaist-cp/rv6/pull/481#discussion_r620885585

여기서 brand()가 임의의 데이터에 같은 brand id를 부여하므로 safety가 문제되지 않나요?

**Comment by Medowhill** [comment]
제가 리뷰할 때 `brand`가 unsafe일 필요가 없다는 데 동의한 이유는 아래와 같습니다.

`Branded<'id, T>`는 어떤 경우에도 자체적인 invariant를 가지지 않습니다. 단순히 branded type을 구현하는 데 필요한 boilerplate code를 줄이는 용도입니다. 제 생각에는 `(T, S)`가 두 타입의 product인 것처럼 `Branded<'id, T>`는 id와 타입의 product로 이해해야 하는 것 같습니다. 따라서 임의의 `Branded<'id, T>` 타입을 마구 만들어 낼 수 있다고 해도 문제되지 않습니다.

반면, `BrandedProcs<'id, T>`와 같은 branded type은 invariant를 가질 수 있습니다. 예를 들면, `BrandedProcs<'id, T>`와 `BrandedKernel<'id, T>` 타입의 값이 같은 id를 공유한다면, 이 `BrandedProcs`가 이 `BrandedKernel`의 procs여야 한다는 invariant가 있습니다. (두 타입 간의 relation으로서 존재하는 invariant라고 해야 할 것 같은데, `BrandedProcs`의 invariant로 볼지, `BrandedKernel`의 invariant로 볼지, 둘 모두의 invariant로 볼지는 아직 모르겠습니다.) 그러므로 `BrandedProcs`는 `Branded<'id, Procs>`를 필드로 가지고 있지만, `Branded<'id, Procs>`로부터 `BrandedProcs`를 만드는 함수는 절대 safe이면 안 됩니다. 주어진 `Branded<'id, Procs>`가 `BrandedProcs`의 invariant를 만족할 때만 `BrandedProcs`를 만들어도 문제가 없기 때문입니다.

현재는 `Branded<'id, Procs>`를 인자로 받아 `BrandedProcs`를 만드는 메서드를 제공하는 대신, `BrandedProcs`의 associated function이 내부에서 `brand`를 호출해 `Branded<'id, Procs>`를 만들고 이를 필드로 하여 `BrandedProcs`를 만들기 때문에 위험한 부분이 없습니다.

**Comment by travis1829** [comment]
저도 비슷한 의견입니다.
`Branded`를 항상 `ProcsRef`와 같은 wrapper로 감싸서 사용하면 문제가 생기지 않는 것 같습니다.
* 임의의 데이터 `T`에 대해, `Branded<'id, T>`는 누구나 만들 수 있습니다.
* 하지만, `ProcsRef<'id, 's>`는 "src/proc.rs" module 내에서만 만들 수 있습니다. 외부에서는 `KernelRef::procs()`를 통해서만 `ProcsRef<'id, 's>`를 얻을 수 있습니다.
* 그러므로, "src/proc.rs" module 내에서만 잘 조심을 하면, **`ProcsRef<'id, 's>`는 항상 동일한 `'id`의 `KernelRef<'id, 's>`로 부터만 올 수 있다"라는 invariant를 유지할 수 있을 것으로 보입니다.

**Comment by jeehoonkang** [comment]
잘 정리해주셔서 감사합니다. 위오 ㅏ같은 논의 내용을 주석으로 상세히 써주시면 감사드리겠습니다.
