### ISSUE TITLE
CI Failures

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#500]
`error: unknown proxy name: 'cargo-fmt'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri'`라는 문구를 출력하면서 CI가 실패합니다.

<https://github.com/kaist-cp/rv6/pull/499/checks?check_run_id=2449454496>

**Comment by jeehoonkang** [comment]
probably a transient error... closing
