### ISSUE TITLE
Adding `Hal` type

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#525]
> 혹시 CPUS와 마찬가지로 특정 kernel에 속한다고 보기 어려운게 또 있을까요? 제 생각으로는 trap.rs도 kernel에 속하지 않는게 아닌가 하는데, 그런 것들을 모두 모아서 "HAL" (hardware abstraction layer) 정도로 이름붙이면 어떨지 생각했습니다.

<https://github.com/kaist-cp/rv6/pull/508#pullrequestreview-648161288>

`Hal` 타입을 추가해야 한다는 제안이 있었습니다. `Hal` 타입에는 `Cpus`, `Uart`, `Console`, `Printer`, `Kmem`이 들어가야 할 것으로 생각됩니다.

**Comment by Medowhill** [comment]
`Uart`가 `Hal`에 들어간다면 `VirtioDisk`도 `Hal`에 들어가야 할까요? `VirtioDisk`도 하드웨어에 대한 abstraction이긴 한데, 여러 커널이 하나의 디스크를 어떻게 공유할 수 있는지는 잘 모르겠습니다.

**Comment by jeehoonkang** [comment]
저는 VirtioDisk도 Hal에 포함되어야 하는게 아닌가 합니다. disk를 어떻게 kernel에 할당할지는 다양한 전략이 있을 수 있어보입니다
- 한 disk는 한 kernel이 독점적으로 사용한다고 볼 수 있고
- 한 disk를 쪼개서 여러 kernel에 나눠줄 수도 있고
- 심지어 아예 file system을 Hal에 넣고 file system access 권한만 kernel에 줄 수도 있습니다.

이러한 전략은 kernel/hypervisor 디자인 이슈이고 Hal 자체는 disk를 가지고 있는걸 선호합니다.

**Comment by Medowhill** [comment]
초기화가 필요한 `Uart`, `Console`,`Kmem`, `VirtioDisk` 등의 타입이 `Hal`에 추가되면 `Hal` 역시 각종 함수와 메서드에 인자로 전달되어야 할 텐데, `Hal` 값을 저장하는 필드를 `KernelCtx`에 추가하는 것이 좋을까요?

**Comment by jeehoonkang** [comment]
전 좀 반반입니다. Hal은 머신에 1개밖에 없음이 보장된 타입이므로 `hal() -> &Hal`로 접근해도 괜찮지 않을까 생각합니다.
