### ISSUE TITLE
Safety of accessing static mutable variables

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#531]
`static mut KERNEL: KernelBuilder`에는 `fn kernel_builder() -> &KernelBuilder`와 `fn kernel_builder_unchecked_pin() -> Pin<&mut KernelBuilder>`를 통해 접근할 수 있습니다. `&mut`과 `&`가 동시에 존재해서는 안 되므로 현재는 두 메서드 모두 unsafe입니다. 마찬가지로, `static mut HAL: Hal`에는 `fn hal() -> &Hal`과 `fn hal_unchecked_pin() -> Pin<&mut Hal>`을 통해 접근할 수 있으며 두 메서드 모두 unsafe입니다.

`kernel_builder`와 `hal`은 아무런 safety condition이 없는 safe 메서드로, 그리고 `kernel_builder_unchecked_pin`과 `hal_unchecked_pin`은 "reference가 존재하지 않는 상태에서 호출되어야 하며 만들어진 `&mut`이 존재하는 동안은 다른 reference를 만들어서는 안 된다"는 조건이 있는 unsafe 메서드로 이해하는 방법도 있을 것 같습니다.

현재 상태 그대로 모두 unsafe로 둘지, shared reference를 제공하는 메서드는 safe로 바꿀지 논의가 필요합니다.

**Comment by jeehoonkang** [comment]
- hal_init()만 노출하자
- main(): main.rs로 옮기면 어떨까?
  + `main.rs`가 특별하게 취급되는 문제...?
