### ISSUE TITLE
Where to place `main()`

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/rv6#532]
`main` 함수를 어디에 둘지 결정하기 위한 이슈입니다.

xv6에서는 `main.c`에 있었고, 현재는 `kernel.rs`에 있습니다. `hal.rs`로 옮기는 방법도 한 가지 선택지입니다. `main.rs`에 넣으려 하면 `main.rs`가 특별하게 취급되어 발생하는 문제가 있을 수 있습니다.

**Comment by Medowhill** [comment]
`main.rs`를 추가하면 다음과 같은 오류가 발생합니다.

```
error[E0463]: can't find crate for `std`
  |
  = note: the `riscv64gc-unknown-none-elfhf-3972588801384535734` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

**Comment by jeehoonkang** [comment]
- https://doc.rust-lang.org/cargo/reference/cargo-targets.html#target-auto-discovery
- `autobins = false`
