### ISSUE TITLE
Performance of fork/sbrk

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/rv6#576]
- 한번 살펴봐야할듯 합니다.
- `lat_ctx`가 혹시 도움이 될지도 모르겠습니다. 다 proc에 관련된 거여서...

**Comment by Medowhill** [comment]
실행 각 구간에 소요되는 clock cycle을 출력해, twochildren test case에서 performance bottleneck이 되는 부분을 찾아 보았습니다. `fork`에서 vm의 `clone`을 호출하는데, `clone`의 시간 차이가 크게 납니다. 구체적으로는, `clone`에서 다음 두 부분의 시간 차이가 큽니다.

## rv6

https://github.com/kaist-cp/rv6/blob/bd17fe4ffab8aa2d7f38c6bb2ba94f077b38111d/kernel-rs/src/vm.rs#L337-L341
`allocator.alloc`과 `copy_from_slice`에 각각 평균 30000 cycle 정도 소모됩니다.
https://github.com/kaist-cp/rv6/blob/bd17fe4ffab8aa2d7f38c6bb2ba94f077b38111d/kernel-rs/src/kalloc.rs#L138
`allocator.alloc`에서는`write_bytes`를 하는데 대부분의 시간이 여기에 사용됩니다.

## xv6

https://github.com/kaist-cp/rv6/blob/bd17fe4ffab8aa2d7f38c6bb2ba94f077b38111d/kernel/vm.c#L312-L314
xv6에는 `kalloc`과 `memmove`가 같은 역할을 하는데, 각각 평균 6000 cycle 정도만 소모됩니다.
https://github.com/kaist-cp/rv6/blob/bd17fe4ffab8aa2d7f38c6bb2ba94f077b38111d/kernel/kalloc.c#L80
`kalloc`에서는 `memset`을 사용합니다.

이유는 모르겠지만, Rust의 `copy_from_slice`와 `write_bytes`가 C의 `memmove`와 `memset`에 비해 성능이 훨씬 떨어지는 것으로 보입니다.

**Comment by jeehoonkang** [comment]
잘 알아봐주셔서 감사합니다. 혹시 rv6에서 memset/memmove를 사용하도록 바꿔서 테스트해볼 수 있을까요?

**Comment by Medowhill** [comment]
성능이 5배 정도 차이 나는데 `memmove`와 `memset`이 최적화할 여지가 많지 않다는 점에서 고민하다가, Rust에서는 1바이트씩 write/copy하고 C에서는 8바이트씩 하는 것이 아닌지 확인해 보았습니다. 실제로 그런 것으로 보이고, 8바이트씩 write/copy하도록 수정하니 성능이 개선됨을 확인했습니다.

```diff
-        let init_value = init_value.unwrap_or(5);
-        page.write_bytes(init_value);
+        let i = init_value.unwrap_or(5);
+        let i = u64::from_le_bytes([i; 8]);
+        let (_, buf, _) = unsafe { page.align_to_mut::<u64>() };
+        buf.fill(i);
```

```diff
-            let src = unsafe { slice::from_raw_parts(pa.into_usize() as *const u8, PGSIZE) };
-            page.copy_from_slice(src);
+            let src = unsafe {
+                slice::from_raw_parts(
+                    pa.into_usize() as *const u64,
+                    PGSIZE / mem::size_of::<u64>(),
+                )
+            };
+            let (_, buf, _) = unsafe { page.align_to_mut::<u64>() };
+            for (d, s) in buf.iter_mut().zip(src.iter()) {
+                *d = *s;
+            }
```

다만, 성능이 개선되긴 했지만 여전히 상당수가 xv6에 비해 2배 이상 느려 추가로 디버깅이 필요해 보입니다. 우선, 다른 곳에서도 write/copy가 비효율적으로 이루어지고 있는지 확인해 보겠습니다.
